package core

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBivarMultivarColormapUpstreamInventoryIsDocumented(t *testing.T) {
	colors := readUpstreamColorsPy(t)
	upstreamRequired := []string{
		"class MultivarColormap:",
		"def __init__(self, colormaps, combination_mode, name='multivariate colormap'):",
		"_api.check_in_list(['sRGB_add', 'sRGB_sub'], combination_mode=combination_mode)",
		"self.n_variates = len(colormaps)",
		"self._rgba_bad = (0.0, 0.0, 0.0, 0.0)",
		"def __call__(self, X, alpha=None, bytes=False, clip=True):",
		"if len(X) != len(self):",
		"rgba[..., :3] += sub_rgba[..., :3]",
		"rgba[..., 3] *= sub_rgba[..., 3]",
		"if self.combination_mode == 'sRGB_sub':",
		"rgba[mask_bad] = self.get_bad()",
		"if not np.iterable(lutshape) or len(lutshape) != len(self):",
		"class BivarColormap:",
		"def __init__(self, N=256, M=256, shape='square', origin=(0, 0),",
		"_api.check_in_list(['square', 'circle', 'ignore', 'circleignore'], shape=shape)",
		"self._rgba_outside = (1.0, 0.0, 1.0, 1.0)",
		"self.n_variates = 2",
		"def __call__(self, X, alpha=None, bytes=False):",
		"if len(X) != 2:",
		"X0 *= self.N",
		"X1 *= self.M",
		"mask_outside = (X0 < 0) | (X1 < 0) | (X0 >= self.N) | (X1 >= self.M)",
		"rgba = self._lut[X0, X1]",
		"rgba[mask_outside] = self._rgba_outside",
		"rgba[mask_bad] = self._rgba_bad",
		"if np.shape(alpha) not in [(), np.shape(X0)]:",
		"def resampled(self, lutshape, transposed=False):",
		"def __getitem__(self, item):",
		"class SegmentedBivarColormap(BivarColormap):",
		"_api.check_shape((None, None, 3), patch=patch)",
		"_image.resample(_patch, self._lut, transform, _image.BILINEAR,",
		"class BivarColormapFromImage(BivarColormap):",
		"if lut.ndim != 3 or lut.shape[2] not in (3, 4):",
		"if lut.dtype == np.uint8:",
		"new_lut[:, :, 3] = 1.",
	}
	for _, phrase := range upstreamRequired {
		if !strings.Contains(colors, phrase) {
			t.Fatalf("upstream bivar/multivar inventory missing %q", phrase)
		}
	}

	cm := readUpstreamMatplotlibFile(t, "cm.py")
	for _, phrase := range []string{
		"from matplotlib._cm_multivar import cmap_families as multivar_cmaps",
		"from matplotlib._cm_bivar import cmaps as bivar_cmaps",
		"_multivar_colormaps = ColormapRegistry(multivar_cmaps)",
		"_bivar_colormaps = ColormapRegistry(bivar_cmaps)",
	} {
		if !strings.Contains(cm, phrase) {
			t.Fatalf("upstream bivar/multivar registry inventory missing %q", phrase)
		}
	}

	for _, name := range []string{"_cm_bivar.py", "_cm_multivar.py"} {
		data, err := os.ReadFile(filepath.Join("..", "third_party", "matplotlib", "lib", "matplotlib", name))
		if err != nil {
			t.Fatalf("read upstream %s: %v", name, err)
		}
		if !strings.Contains(string(data), "auto-generated by https://github.com/trygvrad/multivariate_colormaps") {
			t.Fatalf("upstream %s missing generated-colormap provenance", name)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	doc := string(data)
	requiredDocs := []string{
		"Phase 17.6.5 Bivar/Multivar Upstream API Inventory",
		"`MultivarColormap`",
		"`combination_mode`",
		"`sRGB_add`",
		"`sRGB_sub`",
		"`BivarColormap`",
		"`square`, `circle`, `ignore`, and `circleignore`",
		"`BivarColormapFromImage` accepts `(N, M, 3)` or `(N, M, 4)` lookup tables",
		"`SegmentedBivarColormap`",
		"`_bivar_colormaps`",
		"`_multivar_colormaps`",
		"scalar-mappable integration is multi-variate",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(doc, phrase) {
			t.Fatalf("bivar/multivar inventory docs missing %q", phrase)
		}
	}
}

func TestBivarMultivarGoFitAssessmentIsDocumented(t *testing.T) {
	colorSrc, err := os.ReadFile(filepath.Join("..", "color", "colormap.go"))
	if err != nil {
		t.Fatalf("read color colormap source: %v", err)
	}
	for _, phrase := range []string{
		"type Colormap struct",
		"func (c Colormap) At(t float64) render.Color",
		"func (c Colormap) AtValue(t float64) render.Color",
	} {
		if !strings.Contains(string(colorSrc), phrase) {
			t.Fatalf("local scalar colormap source missing %q", phrase)
		}
	}

	scalarSrc, err := os.ReadFile(filepath.Join("..", "core", "scalar_mappable.go"))
	if err != nil {
		t.Fatalf("read scalar mappable source: %v", err)
	}
	for _, phrase := range []string{
		"type ScalarMapInfo struct",
		"Colormap string",
		"Norm     ScalarNormalizer",
		"func (m ScalarMapInfo) Color(v, alpha float64) render.Color",
		"func ResolveScalarMapValues(values []float64, cfg ScalarMapConfig)",
	} {
		if !strings.Contains(string(scalarSrc), phrase) {
			t.Fatalf("local scalar mappable source missing %q", phrase)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	doc := string(data)
	requiredDocs := []string{
		"Phase 17.6.5 Bivar/Multivar Go Fit Assessment",
		"`color.Colormap` maps one",
		"normalized `float64`",
		"`ScalarMapInfo` stores one colormap name, one norm, and",
		"one scalar range",
		"do not fit the current scalar colormap",
		"separate typed surface",
		"hidden mode of `color.Colormap`",
		"colorbar expectations would also",
		"need a new contract",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(doc, phrase) {
			t.Fatalf("bivar/multivar Go fit docs missing %q", phrase)
		}
	}
}

func TestBivarColormapAPIShapeDecisionIsDocumented(t *testing.T) {
	for _, dir := range []string{"color", "core"} {
		root := filepath.Join("..", dir)
		err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || filepath.Ext(path) != ".go" || filepath.Base(path) == "colormap_inventory_test.go" {
				return nil
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			src := string(data)
			for _, phrase := range []string{"type BivarColormap", "BivarColormapFromImage", "SegmentedBivarColormap"} {
				if strings.Contains(src, phrase) {
					t.Fatalf("%s unexpectedly exposes bivariate colormap API via %q", path, phrase)
				}
			}
			return nil
		})
		if err != nil {
			t.Fatalf("scan %s for bivariate API: %v", dir, err)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	doc := string(data)
	requiredDocs := []string{
		"Phase 17.6.5 Bivariate API Shape Decision",
		"`color.BivarColormap`",
		"no `BivarColormapFromImage`",
		"`SegmentedBivarColormap`",
		"future API would need",
		"`N`, `M`, `shape`, and",
		"`origin`",
		"`(N, M, 3)` or `(N, M, 4)`",
		"bad and outside colors",
		"two-component input",
		"2D colorbar contract",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(doc, phrase) {
			t.Fatalf("bivariate API shape docs missing %q", phrase)
		}
	}
}

func TestBivarColormapOmissionIsDocumented(t *testing.T) {
	refDir := filepath.Join("..", "test", "matplotlib_ref", "plots")
	forbidden := []string{"BivarColormap", "bivar", "_bivar_colormaps"}
	err := filepath.WalkDir(refDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".py" {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		src := string(data)
		for _, phrase := range forbidden {
			if strings.Contains(src, phrase) {
				t.Fatalf("%s unexpectedly requires bivariate colormap API via %q", path, phrase)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("scan matplotlib reference plots: %v", err)
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	doc := string(data)
	requiredDocs := []string{
		"Phase 17.6.5 Bivariate Colormap Omission Ledger",
		"`BivarColormap`",
		"`BivarColormapFromImage`",
		"`SegmentedBivarColormap`",
		"intentional omissions",
		"affected examples are",
		"currently none",
		"no committed parity fixture",
		"imports or calls a bivariate",
		"single-variate `color.Colormap`",
		"remains",
		"Future bivariate support should start with a visual",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(doc, phrase) {
			t.Fatalf("bivariate omission docs missing %q", phrase)
		}
	}
}

func TestMultivarColormapAPIShapeDecisionIsDocumented(t *testing.T) {
	for _, dir := range []string{"color", "core"} {
		root := filepath.Join("..", dir)
		err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || filepath.Ext(path) != ".go" || filepath.Base(path) == "colormap_inventory_test.go" {
				return nil
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if strings.Contains(string(data), "MultivarColormap") {
				t.Fatalf("%s unexpectedly exposes multivariate colormap API", path)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("scan %s for multivariate API: %v", dir, err)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	doc := string(data)
	docText := strings.Join(strings.Fields(doc), " ")
	requiredDocs := []string{
		"Phase 17.6.5 Multivariate API Shape Decision",
		"no `color.MultivarColormap`",
		"future API would need a component-colormap list",
		"`combination_mode`",
		"`sRGB_add`",
		"`sRGB_sub`",
		"tuple input with one component per variate",
		"component alpha multiplication",
		"multi-component colorbar contract",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(docText, phrase) {
			t.Fatalf("multivariate API shape docs missing %q", phrase)
		}
	}
}

func TestMultivarColormapOmissionIsDocumented(t *testing.T) {
	for _, refDir := range []string{
		filepath.Join("..", "test", "matplotlib_ref", "plots"),
		filepath.Join("..", "test", "parity"),
	} {
		err := filepath.WalkDir(refDir, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || filepath.Ext(path) != ".py" && filepath.Ext(path) != ".go" {
				return nil
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			src := string(data)
			for _, phrase := range []string{"MultivarColormap", "multivar", "_multivar_colormaps", "combination_mode"} {
				if strings.Contains(src, phrase) {
					t.Fatalf("%s unexpectedly requires multivariate colormap API via %q", path, phrase)
				}
			}
			return nil
		})
		if err != nil {
			t.Fatalf("scan %s for multivariate API fixtures: %v", refDir, err)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	docText := strings.Join(strings.Fields(string(data)), " ")
	requiredDocs := []string{
		"Phase 17.6.5 Multivariate Colormap Omission Ledger",
		"`MultivarColormap`",
		"`combination_mode`",
		"`sRGB_add`",
		"`sRGB_sub`",
		"intentional omission",
		"affected examples are currently none",
		"no committed parity fixture imports or calls a multivariate colormap",
		"single-variate `color.Colormap` remains",
		"Future multivariate support should start with a focused visual or scalar-mappable fixture",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(docText, phrase) {
			t.Fatalf("multivariate omission docs missing %q", phrase)
		}
	}
}

func TestFocusedColormapLookupTestsAreDocumented(t *testing.T) {
	colorTests, err := os.ReadFile(filepath.Join("..", "color", "colormap_test.go"))
	if err != nil {
		t.Fatalf("read color colormap tests: %v", err)
	}
	if !strings.Contains(string(colorTests), "TestScalarColormapLookupCoversShapeAlphaAndBadValues") {
		t.Fatal("missing focused scalar colormap lookup test")
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	docText := strings.Join(strings.Fields(string(data)), " ")
	requiredDocs := []string{
		"Phase 17.6.5 Focused Colormap Lookup Tests",
		"implemented lookup path is single-variate `color.Colormap`",
		"listed lookup-table quantization",
		"linear-segment alpha interpolation",
		"bad, under, and over colors",
		"`AtValue`",
		"bivariate and multivariate lookup tables remain omission-only",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(docText, phrase) {
			t.Fatalf("focused lookup docs missing %q", phrase)
		}
	}
}

func TestBivarMultivarOmissionDiagnosticsAreDocumented(t *testing.T) {
	testSrc, err := os.ReadFile(filepath.Join("colormap_inventory_test.go"))
	if err != nil {
		t.Fatalf("read colormap inventory tests: %v", err)
	}
	for _, phrase := range []string{
		"TestBivarColormapOmissionIsDocumented",
		"TestMultivarColormapOmissionIsDocumented",
		"test/matplotlib_ref",
		"test/parity",
	} {
		if !strings.Contains(string(testSrc), phrase) {
			t.Fatalf("omission diagnostics missing coverage marker %q", phrase)
		}
	}

	data, err := os.ReadFile(filepath.Join("..", "docs", "matplotlib-migration-notes.md"))
	if err != nil {
		t.Fatalf("read migration notes: %v", err)
	}
	docText := strings.Join(strings.Fields(string(data)), " ")
	requiredDocs := []string{
		"Phase 17.6.5 Colormap Omission Diagnostics",
		"unsupported bivariate inputs are two-component lookup-table inputs",
		"unsupported multivariate inputs are tuple-valued component arrays",
		"no Go artist accepts tuple-valued colormap input",
		"fixture scans cover `test/matplotlib_ref/plots` and `test/parity`",
		"covered by `TestBivarColormapOmissionIsDocumented`",
		"covered by `TestMultivarColormapOmissionIsDocumented`",
	}
	for _, phrase := range requiredDocs {
		if !strings.Contains(docText, phrase) {
			t.Fatalf("colormap omission diagnostics docs missing %q", phrase)
		}
	}
}
