package core

import (
	"math"
	"slices"
	"strings"

	"github.com/cwbudde/matplotlib-go/internal/geom"
	"github.com/cwbudde/matplotlib-go/render"
)

// HexbinOptions configures Axes.Hexbin.
type HexbinOptions struct {
	GridSizeX int
	GridSizeY int
	Extent    *geom.Rect
	C         []float64
	Reduce    string
	Bins      string
	BinCount  int
	BinEdges  []float64
	XScale    string
	YScale    string
	Marginals bool
	MinCount  int
	Colormap  string
	Norm      ScalarNormalizer
	VMin      *float64
	VMax      *float64
	Alpha     float64
	EdgeColor *render.Color
	LineWidth float64
	Label     string
}

// HexbinCollection is a scalar-mappable polygon collection generated by hexbin.
type HexbinCollection struct {
	PolyCollection
	BinCenters []geom.Pt
	Values     []float64
	Counts     []float64
	HBar       *PolyCollection
	VBar       *PolyCollection
}

type hexbinKey struct {
	lattice  int
	row, col int
}

type hexbinBin struct {
	center geom.Pt
	count  float64
	sum    float64
	values []float64
}

// Hexbin bins points into a staggered hexagonal grid and colors occupied bins by aggregate value.
func (a *Axes) Hexbin(x, y []float64, opts ...HexbinOptions) *HexbinCollection {
	if a == nil || len(x) == 0 || len(y) == 0 {
		return nil
	}

	n := min(len(x), len(y))
	cfg := HexbinOptions{
		GridSizeX: 18,
		MinCount:  1,
		Colormap:  "viridis",
		Alpha:     1,
		LineWidth: 0.75,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.GridSizeX <= 0 {
			cfg.GridSizeX = 18
		}
		if cfg.MinCount <= 0 {
			cfg.MinCount = 1
		}
		if cfg.Colormap == "" {
			cfg.Colormap = "viridis"
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 0.75
		}
	}
	xscale := normalizeHexScale(cfg.XScale)
	yscale := normalizeHexScale(cfg.YScale)

	extent := cfg.Extent
	if extent == nil {
		tx, ty := specialtyHexbinScaledPoints(x[:n], y[:n], xscale, yscale)
		rect := finitePointRect(tx, ty)
		extent = &rect
	}
	if extent.W() == 0 {
		extent.Max.X = extent.Min.X + 1
	}
	if extent.H() == 0 {
		extent.Max.Y = extent.Min.Y + 1
	}

	gridX := max(1, cfg.GridSizeX)
	gridY := cfg.GridSizeY
	if gridY <= 0 {
		gridY = max(1, int(float64(gridX)/math.Sqrt(3)))
	}

	xMin, xMax := extent.Min.X, extent.Max.X
	yMin, yMax := extent.Min.Y, extent.Max.Y
	padding := 1e-9 * (xMax - xMin)
	xMin -= padding
	xMax += padding

	xStep := (xMax - xMin) / float64(gridX)
	yStep := (yMax - yMin) / float64(gridY)
	if xStep <= 0 {
		xStep = 1
	}
	if yStep <= 0 {
		yStep = 1
	}

	bins := map[hexbinKey]*hexbinBin{}
	for i := range n {
		xi, yi := specialtyHexbinScaledPoint(x[i], y[i], xscale, yscale)
		if !isFinite(xi) || !isFinite(yi) {
			continue
		}
		k, center, ok := matplotlibHexbinCenter(xi, yi, xMin, yMin, gridX, gridY, xStep, yStep)
		if !ok {
			continue
		}
		entry := bins[k]
		if entry == nil {
			entry = &hexbinBin{
				center: center,
			}
			bins[k] = entry
		}
		entry.count++
		if i < len(cfg.C) && isFinite(cfg.C[i]) {
			entry.sum += cfg.C[i]
			entry.values = append(entry.values, cfg.C[i])
		} else {
			entry.sum += 1
		}
	}
	if len(bins) == 0 {
		return nil
	}

	keys := make([]hexbinKey, 0, len(bins))
	for k := range bins {
		keys = append(keys, k)
	}
	slices.SortFunc(keys, func(a, b hexbinKey) int {
		if a.lattice != b.lattice {
			return a.lattice - b.lattice
		}
		if a.row != b.row {
			return a.row - b.row
		}
		return a.col - b.col
	})

	polygons := make([][]geom.Pt, 0, len(keys))
	values := make([]float64, 0, len(keys))
	counts := make([]float64, 0, len(keys))
	centers := make([]geom.Pt, 0, len(keys))
	rx := xStep / 2
	ry := yStep / 3
	for _, k := range keys {
		entry := bins[k]
		if int(entry.count) < cfg.MinCount {
			continue
		}
		value := entry.count
		if len(cfg.C) > 0 {
			value = reduceHexbinValues(entry, cfg.Reduce)
		}
		center := specialtyHexbinUnscalePoint(entry.center, xscale, yscale)
		scaledPolygon := specialtyHexagon(entry.center, rx, ry)
		polygon := make([]geom.Pt, len(scaledPolygon))
		for i, pt := range scaledPolygon {
			polygon[i] = specialtyHexbinUnscalePoint(pt, xscale, yscale)
		}
		polygons = append(polygons, polygon)
		values = append(values, value)
		counts = append(counts, entry.count)
		centers = append(centers, center)
	}
	if len(polygons) == 0 {
		return nil
	}
	values = applyHexbinBins(values, cfg)
	norm := cfg.Norm
	if strings.EqualFold(cfg.Bins, "log") && norm == nil {
		norm = LogNorm{VMin: math.NaN(), VMax: math.NaN()}
	}

	mapping, err := ResolveScalarMapValues(values, ScalarMapConfig{
		Colormap: cfg.Colormap,
		Norm:     norm,
		VMin:     cfg.VMin,
		VMax:     cfg.VMax,
	})
	if err != nil {
		return nil
	}
	faceColors := make([]render.Color, len(values))
	for i, value := range values {
		faceColors[i] = mapping.Color(value, cfg.Alpha)
	}
	edgeColor := render.Color{R: 1, G: 1, B: 1, A: 0.9}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}
	edgeColors := faceColors
	if cfg.EdgeColor != nil {
		edgeColors = nil
	}
	collection := &HexbinCollection{
		PolyCollection: PolyCollection{
			PatchCollection: PatchCollection{
				Collection: Collection{
					Label:    cfg.Label,
					Alpha:    1,
					Colormap: mapping.Colormap,
					Norm:     mapping.Norm,
					VMin:     mapping.VMin,
					VMax:     mapping.VMax,
					z:        2,
				},
				FaceColors: faceColors,
				EdgeColor:  edgeColor,
				EdgeColors: edgeColors,
				EdgeWidth:  cfg.LineWidth,
			},
			Polygons: polygons,
		},
		BinCenters: centers,
		Values:     values,
		Counts:     counts,
	}
	if cfg.Marginals {
		collection.HBar, collection.VBar = specialtyHexbinMarginals(x[:n], y[:n], cfg, xscale, yscale, mapping)
		if collection.HBar != nil {
			a.AddCollection(collection.HBar)
		}
		if collection.VBar != nil {
			a.AddCollection(collection.VBar)
		}
	}
	a.AddCollection(collection)
	if xscale == "log" {
		_ = a.SetXScale("log")
	}
	if yscale == "log" {
		_ = a.SetYScale("log")
	}
	return collection
}

func specialtyHexagon(center geom.Pt, rx, ry float64) []geom.Pt {
	return []geom.Pt{
		{X: center.X + rx, Y: center.Y - ry/2},
		{X: center.X + rx, Y: center.Y + ry/2},
		{X: center.X, Y: center.Y + ry},
		{X: center.X - rx, Y: center.Y + ry/2},
		{X: center.X - rx, Y: center.Y - ry/2},
		{X: center.X, Y: center.Y - ry},
	}
}

func matplotlibHexbinCenter(x, y, xMin, yMin float64, gridX, gridY int, xStep, yStep float64) (hexbinKey, geom.Pt, bool) {
	ix := (x - xMin) / xStep
	iy := (y - yMin) / yStep
	ix1 := int(math.Round(ix))
	iy1 := int(math.Round(iy))
	ix2 := int(math.Floor(ix))
	iy2 := int(math.Floor(iy))

	valid1 := 0 <= ix1 && ix1 <= gridX && 0 <= iy1 && iy1 <= gridY
	valid2 := 0 <= ix2 && ix2 < gridX && 0 <= iy2 && iy2 < gridY
	if !valid1 && !valid2 {
		return hexbinKey{}, geom.Pt{}, false
	}
	d1 := math.Inf(1)
	if valid1 {
		d1 = (ix-float64(ix1))*(ix-float64(ix1)) + 3*(iy-float64(iy1))*(iy-float64(iy1))
	}
	d2 := math.Inf(1)
	if valid2 {
		d2 = (ix-float64(ix2)-0.5)*(ix-float64(ix2)-0.5) + 3*(iy-float64(iy2)-0.5)*(iy-float64(iy2)-0.5)
	}
	if d1 < d2 {
		return hexbinKey{lattice: 0, row: iy1, col: ix1}, geom.Pt{
			X: xMin + float64(ix1)*xStep,
			Y: yMin + float64(iy1)*yStep,
		}, true
	}
	return hexbinKey{lattice: 1, row: iy2, col: ix2}, geom.Pt{
		X: xMin + (float64(ix2)+0.5)*xStep,
		Y: yMin + (float64(iy2)+0.5)*yStep,
	}, true
}

func normalizeHexScale(value string) string {
	if strings.EqualFold(strings.TrimSpace(value), "log") {
		return "log"
	}
	return "linear"
}

func specialtyHexbinScaledPoints(x, y []float64, xscale, yscale string) ([]float64, []float64) {
	n := min(len(x), len(y))
	tx := make([]float64, n)
	ty := make([]float64, n)
	for i := range n {
		tx[i], ty[i] = specialtyHexbinScaledPoint(x[i], y[i], xscale, yscale)
	}
	return tx, ty
}

func specialtyHexbinScaledPoint(x, y float64, xscale, yscale string) (float64, float64) {
	if xscale == "log" {
		if x <= 0 {
			x = math.NaN()
		} else {
			x = math.Log10(x)
		}
	}
	if yscale == "log" {
		if y <= 0 {
			y = math.NaN()
		} else {
			y = math.Log10(y)
		}
	}
	return x, y
}

func specialtyHexbinUnscalePoint(pt geom.Pt, xscale, yscale string) geom.Pt {
	if xscale == "log" {
		pt.X = math.Pow(10, pt.X)
	}
	if yscale == "log" {
		pt.Y = math.Pow(10, pt.Y)
	}
	return pt
}

func reduceHexbinValues(entry *hexbinBin, reduce string) float64 {
	if entry == nil {
		return math.NaN()
	}
	switch strings.ToLower(strings.TrimSpace(reduce)) {
	case "sum":
		return entry.sum
	case "count", "len":
		return entry.count
	case "min", "minimum":
		if len(entry.values) == 0 {
			return math.NaN()
		}
		out := entry.values[0]
		for _, v := range entry.values[1:] {
			out = math.Min(out, v)
		}
		return out
	case "max", "maximum", "amax":
		if len(entry.values) == 0 {
			return math.NaN()
		}
		out := entry.values[0]
		for _, v := range entry.values[1:] {
			out = math.Max(out, v)
		}
		return out
	default:
		if entry.count == 0 {
			return math.NaN()
		}
		return entry.sum / entry.count
	}
}

func applyHexbinBins(values []float64, cfg HexbinOptions) []float64 {
	if cfg.BinCount <= 0 && len(cfg.BinEdges) == 0 {
		return values
	}
	out := append([]float64(nil), values...)
	edges := append([]float64(nil), cfg.BinEdges...)
	if len(edges) == 0 && cfg.BinCount > 1 {
		minValue, maxValue := finiteRange(out)
		if isFinite(minValue) && isFinite(maxValue) && minValue != maxValue {
			steps := cfg.BinCount - 1
			for i := 0; i < steps; i++ {
				edges = append(edges, minValue+(maxValue-minValue)*float64(i)/float64(steps))
			}
		}
	}
	if len(edges) == 0 {
		return out
	}
	slices.Sort(edges)
	for i, value := range out {
		out[i] = float64(slices.IndexFunc(edges, func(edge float64) bool {
			return value < edge
		}))
		if out[i] < 0 {
			out[i] = float64(len(edges))
		}
	}
	return out
}

func specialtyHexbinMarginals(x, y []float64, cfg HexbinOptions, xscale, yscale string, mapping ScalarMapInfo) (*PolyCollection, *PolyCollection) {
	extent := cfg.Extent
	if extent == nil {
		tx, ty := specialtyHexbinScaledPoints(x, y, xscale, yscale)
		rect := finitePointRect(tx, ty)
		extent = &rect
	}
	gridX := max(1, cfg.GridSizeX)
	gridY := cfg.GridSizeY
	if gridY <= 0 {
		gridY = max(1, int(float64(gridX)/math.Sqrt(3)))
	}
	xMin, xMax := extent.Min.X, extent.Max.X
	yMin, yMax := extent.Min.Y, extent.Max.Y
	if xscale == "log" {
		xMin, xMax = math.Pow(10, xMin), math.Pow(10, xMax)
	}
	if yscale == "log" {
		yMin, yMax = math.Pow(10, yMin), math.Pow(10, yMax)
	}
	hbar := specialtyMarginalBars(x, cfg.C, xMin, xMax, gridX, xscale, true, cfg.Reduce, mapping, cfg.Alpha)
	vbar := specialtyMarginalBars(y, cfg.C, yMin, yMax, 2*gridY, yscale, false, cfg.Reduce, mapping, cfg.Alpha)
	return hbar, vbar
}

func specialtyMarginalBars(values, cvalues []float64, minValue, maxValue float64, bins int, scale string, horizontal bool, reduce string, mapping ScalarMapInfo, alpha float64) *PolyCollection {
	if bins <= 0 || minValue == maxValue {
		return nil
	}
	edges := marginalBinEdges(minValue, maxValue, bins, scale)
	if len(edges) != bins+1 {
		return nil
	}
	binned := make([][]float64, bins)
	for i, value := range values {
		if !isFinite(value) || (scale == "log" && value <= 0) {
			continue
		}
		idx := marginalBinIndex(edges, value)
		if idx < 0 || idx >= bins {
			continue
		}
		c := 1.0
		if i < len(cvalues) && isFinite(cvalues[i]) {
			c = cvalues[i]
		}
		binned[idx] = append(binned[idx], c)
	}
	polys := make([][]geom.Pt, 0, bins)
	colors := make([]render.Color, 0, bins)
	for i, bucket := range binned {
		if len(bucket) == 0 {
			continue
		}
		value := reduceMarginalValues(bucket, reduce)
		a := edges[i]
		b := edges[i+1]
		if horizontal {
			polys = append(polys, []geom.Pt{{X: a, Y: 0}, {X: b, Y: 0}, {X: b, Y: 0.05}, {X: a, Y: 0.05}})
		} else {
			polys = append(polys, []geom.Pt{{X: 0, Y: a}, {X: 0.05, Y: a}, {X: 0.05, Y: b}, {X: 0, Y: b}})
		}
		colors = append(colors, mapping.Color(value, alpha))
	}
	if len(polys) == 0 {
		return nil
	}
	coords := BlendCoords(CoordData, CoordAxes)
	if !horizontal {
		coords = BlendCoords(CoordAxes, CoordData)
	}
	return &PolyCollection{
		PatchCollection: PatchCollection{
			Collection: Collection{Coords: coords, Alpha: 1, z: 2.1},
			FaceColors: colors,
			EdgeColors: colors,
			EdgeWidth:  0,
		},
		Polygons: polys,
	}
}

func marginalBinEdges(minValue, maxValue float64, bins int, scale string) []float64 {
	edges := make([]float64, bins+1)
	if scale == "log" {
		if minValue <= 0 || maxValue <= 0 {
			return nil
		}
		lo := math.Log10(minValue)
		hi := math.Log10(maxValue)
		for i := range edges {
			edges[i] = math.Pow(10, lo+(hi-lo)*float64(i)/float64(bins))
		}
		return edges
	}
	for i := range edges {
		edges[i] = minValue + (maxValue-minValue)*float64(i)/float64(bins)
	}
	return edges
}

func marginalBinIndex(edges []float64, value float64) int {
	idx := slices.IndexFunc(edges, func(edge float64) bool {
		return value < edge
	}) - 1
	if idx < 0 && len(edges) > 0 && value == edges[0] {
		return 0
	}
	if idx == len(edges)-1 && value == edges[len(edges)-1] {
		return idx - 1
	}
	return idx
}

func reduceMarginalValues(values []float64, reduce string) float64 {
	entry := &hexbinBin{count: float64(len(values)), values: append([]float64(nil), values...)}
	for _, value := range values {
		entry.sum += value
	}
	return reduceHexbinValues(entry, reduce)
}

func finitePointRect(x, y []float64) geom.Rect {
	var rect geom.Rect
	have := false
	for i := 0; i < min(len(x), len(y)); i++ {
		if !isFinite(x[i]) || !isFinite(y[i]) {
			continue
		}
		pt := geom.Pt{X: x[i], Y: y[i]}
		if !have {
			rect = geom.Rect{Min: pt, Max: pt}
			have = true
			continue
		}
		rect = expandRect(rect, pt)
	}
	if !have {
		return geom.Rect{Min: geom.Pt{}, Max: geom.Pt{X: 1, Y: 1}}
	}
	return rect
}
