package core

import (
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/cwbudde/matplotlib-go/internal/geom"
	"github.com/cwbudde/matplotlib-go/render"
)

// EventOrientation controls whether eventplot lines are drawn vertically or horizontally.
type EventOrientation uint8

const (
	EventOrientationVertical EventOrientation = iota
	EventOrientationHorizontal
)

// EventPlotOptions configures Axes.Eventplot.
type EventPlotOptions struct {
	Orientation EventOrientation
	LineOffsets []float64
	LineLengths []float64
	Colors      []render.Color
	LineWidth   float64
	Alpha       float64
	Label       string
}

// EventCollection is a thin LineCollection wrapper used for eventplot.
type EventCollection struct {
	LineCollection
	Positions   [][]float64
	Orientation EventOrientation
	LineOffsets []float64
	LineLengths []float64
}

// HexbinOptions configures Axes.Hexbin.
type HexbinOptions struct {
	GridSizeX int
	GridSizeY int
	Extent    *geom.Rect
	C         []float64
	Reduce    string
	Bins      string
	BinCount  int
	BinEdges  []float64
	XScale    string
	YScale    string
	Marginals bool
	MinCount  int
	Colormap  string
	Norm      ScalarNormalizer
	VMin      *float64
	VMax      *float64
	Alpha     float64
	EdgeColor *render.Color
	LineWidth float64
	Label     string
}

// HexbinCollection is a scalar-mappable polygon collection generated by hexbin.
type HexbinCollection struct {
	PolyCollection
	BinCenters []geom.Pt
	Values     []float64
	Counts     []float64
	HBar       *PolyCollection
	VBar       *PolyCollection
}

type hexbinKey struct {
	lattice  int
	row, col int
}

type hexbinBin struct {
	center geom.Pt
	count  float64
	sum    float64
	values []float64
}

// PieOptions configures Axes.Pie.
type PieOptions struct {
	Center           geom.Pt
	Radius           float64
	Width            float64
	StartAngle       float64
	CounterClockwise *bool
	Colors           []render.Color
	Labels           []string
	Explode          []float64
	AutoPct          string
	LabelDistance    float64
	PctDistance      float64
	RotateLabels     bool
	Normalize        *bool
	Hatch            string
	Hatches          []string
	HatchColor       render.Color
	HatchWidth       float64
	Shadow           bool
	ShadowOffset     geom.Pt
	ShadowColor      render.Color
	EdgeColor        *render.Color
	LineWidth        float64
	Alpha            float64
	Coords           CoordinateSpec
	Frame            *bool
}

// PieContainer groups the wedge and text artists created by Axes.Pie.
type PieContainer struct {
	Wedges      []*Wedge
	Shadows     []*Wedge
	Labels      []*Text
	AutoText    []*Text
	LabelAngles []float64
}

type PieLabelOptions struct {
	Distance  float64
	Rotate    bool
	Alignment string
	Coords    CoordinateSpec
}

// ViolinOptions configures Axes.Violinplot.
type ViolinOptions struct {
	Positions       []float64
	Widths          []float64
	Colors          []render.Color
	EdgeColor       *render.Color
	EdgeWidth       float64
	Alpha           float64
	Bandwidth       float64
	BandwidthMethod string
	Points          int
	Orientation     string
	Side            string
	Quantiles       [][]float64
	LineColor       *render.Color
	ShowMeans       *bool
	ShowMedians     *bool
	ShowExtrema     *bool
	Label           string
}

// ViolinContainer groups the collections created by Axes.Violinplot.
type ViolinContainer struct {
	Bodies    *PolyCollection
	Means     *LineCollection
	Medians   *LineCollection
	Quantiles *LineCollection
	Extrema   *LineCollection
}

// TableOptions configures Axes.Table.
type TableOptions struct {
	CellText        [][]string
	CellColors      [][]render.Color
	RowLabels       []string
	ColLabels       []string
	BBox            geom.Rect
	Coords          CoordinateSpec
	FontSize        float64
	TextColor       render.Color
	HeaderTextColor render.Color
	HeaderFillColor render.Color
	CellFillColor   render.Color
	EdgeColor       render.Color
	LineWidth       float64
	CellLoc         string
	RowLoc          string
	ColLoc          string
}

type tableCell struct {
	Text     string
	Fill     render.Color
	IsHeader bool
	Rect     geom.Rect
	HAlign   TextAlign
}

// Table renders a simple grid of cells with optional row and column headers.
type Table struct {
	Cells           [][]tableCell
	BBox            geom.Rect
	Coords          CoordinateSpec
	FontSize        float64
	TextColor       render.Color
	HeaderTextColor render.Color
	EdgeColor       render.Color
	LineWidth       float64
	z               float64
}

// SankeyOptions configures a lightweight builder for Sankey-like ribbon diagrams.
type SankeyOptions struct {
	Center      geom.Pt
	Coords      CoordinateSpec
	Scale       float64
	TrunkWidth  float64
	TrunkLength float64
	PathLength  float64
	Gap         float64
	Radius      float64
	Shoulder    float64
	Offset      float64
	HeadAngle   float64
	Margin      float64
	Tolerance   float64
	Alpha       float64
	TextColor   render.Color
	FontSize    float64
	EdgeColor   *render.Color
	FaceColor   *render.Color
}

// SankeyAddOptions configures one diagram added through the builder.
type SankeyAddOptions struct {
	Labels       []string
	Orientations []int
	Colors       []render.Color
	OffsetX      float64
	OffsetY      float64
	TrunkLength  float64
	PathLength   float64
	PatchLabel   string
	Rotation     float64
}

// Sankey accumulates one or more simple ribbon diagrams on a single axes.
type Sankey struct {
	ax         *Axes
	opts       SankeyOptions
	diagrams   []*SankeyDiagram
	cursor     geom.Pt
	pitch      float64
	extent     geom.Rect
	haveExtent bool
}

// SankeyDiagram groups the artists emitted for one builder Add call.
type SankeyDiagram struct {
	Trunk   *Rectangle
	Patch   *PathPatch
	Ribbons []*PathPatch
	Text    *Text
	Labels  []*Text
	Values  []*Text
	Flows   []float64
	Angles  []int
	Tips    []geom.Pt
	Center  geom.Pt
	Extent  geom.Rect
}

// Wedge draws a pie-slice-style circular sector or ring segment.
type Wedge struct {
	Patch
	Center geom.Pt
	Radius float64
	Width  float64
	Theta1 float64
	Theta2 float64
	Coords CoordinateSpec
}

const (
	sankeyRight = 0
	sankeyUp    = 1
	sankeyDown  = 3
	sankeyNone  = -1
)

type sankeyPathCmd uint8

const (
	sankeyMoveTo sankeyPathCmd = iota
	sankeyLineTo
	sankeyCurveTo
	sankeyClosePath
)

type sankeyPathStep struct {
	cmd sankeyPathCmd
	pt  geom.Pt
}

// Add supports the Matplotlib-style builder workflow: create one diagram and
// append its artists to the axes immediately.
func (s *Sankey) Add(flows []float64, opts ...SankeyAddOptions) *SankeyDiagram {
	if s == nil || s.ax == nil || len(flows) == 0 {
		return nil
	}

	cfg := SankeyAddOptions{}
	if len(opts) > 0 {
		cfg = opts[0]
	}

	scale := s.opts.Scale
	if scale <= 0 {
		scale = 1
	}
	alpha := clampOneToOne(s.opts.Alpha)
	if alpha == 0 {
		alpha = 1
	}
	edgeColor := render.Color{R: 0, G: 0, B: 0, A: 1}
	if s.opts.EdgeColor != nil {
		edgeColor = *s.opts.EdgeColor
	}
	defaultFace := s.ax.NextColor()
	if s.opts.FaceColor != nil {
		defaultFace = *s.opts.FaceColor
	}

	center := geom.Pt{X: s.cursor.X + cfg.OffsetX, Y: s.cursor.Y + cfg.OffsetY}
	trunkLength := s.opts.TrunkLength
	if cfg.TrunkLength > 0 {
		trunkLength = cfg.TrunkLength
	}
	if trunkLength < 0 {
		trunkLength = 0
	}
	pathLength := s.opts.PathLength
	if cfg.PathLength > 0 {
		pathLength = cfg.PathLength
	}
	if pathLength < 0 {
		pathLength = 0
	}
	tolerance := s.opts.Tolerance
	if tolerance <= 0 {
		tolerance = 1e-6
	}

	scaledFlows := make([]float64, len(flows))
	gain := 0.0
	loss := 0.0
	for i, flow := range flows {
		scaledFlows[i] = scale * flow
		if scaledFlows[i] > 0 {
			gain += scaledFlows[i]
		} else if scaledFlows[i] < 0 {
			loss += scaledFlows[i]
		}
	}

	areInputs := make([]bool, len(flows))
	showFlow := make([]bool, len(flows))
	for i, flow := range flows {
		switch {
		case flow >= tolerance:
			areInputs[i] = true
			showFlow[i] = true
		case flow <= -tolerance:
			showFlow[i] = true
		}
	}
	if !sankeyHasVisibleFlow(showFlow) {
		return nil
	}

	orientations := sankeyBroadcastInts(cfg.Orientations, len(flows), 0)
	angles := make([]int, len(flows))
	for i := range angles {
		angles[i] = sankeyNone
		if !showFlow[i] {
			continue
		}
		switch orientations[i] {
		case 1:
			if areInputs[i] {
				angles[i] = sankeyDown
			} else {
				angles[i] = sankeyUp
			}
		case 0:
			angles[i] = sankeyRight
		case -1:
			if areInputs[i] {
				angles[i] = sankeyUp
			} else {
				angles[i] = sankeyDown
			}
		default:
			angles[i] = sankeyRight
		}
	}

	pathLengths := sankeyJustifiedPathLengths(pathLength, scaledFlows, areInputs, showFlow, angles)
	urpath, llpath, lrpath, ulpath := sankeyInitialPaths(s.opts.Gap, trunkLength, gain, loss)

	tips := make([]geom.Pt, len(flows))
	labelLocations := make([]geom.Pt, len(flows))
	for i := range flows {
		if angles[i] == sankeyDown && areInputs[i] {
			tips[i], labelLocations[i] = s.sankeyAddInput(&ulpath, angles[i], scaledFlows[i], pathLengths[i])
		} else if angles[i] == sankeyUp && !areInputs[i] && showFlow[i] {
			tips[i], labelLocations[i] = s.sankeyAddOutput(&urpath, angles[i], scaledFlows[i], pathLengths[i])
		}
	}
	for i := len(flows) - 1; i >= 0; i-- {
		if angles[i] == sankeyUp && areInputs[i] {
			tips[i], labelLocations[i] = s.sankeyAddInput(&llpath, angles[i], scaledFlows[i], pathLengths[i])
		} else if angles[i] == sankeyDown && !areInputs[i] && showFlow[i] {
			tips[i], labelLocations[i] = s.sankeyAddOutput(&lrpath, angles[i], scaledFlows[i], pathLengths[i])
		}
	}
	hasLeftInput := false
	for i := len(flows) - 1; i >= 0; i-- {
		if angles[i] != sankeyRight || !areInputs[i] {
			continue
		}
		if !hasLeftInput {
			if sankeyLastPoint(llpath).X > sankeyLastPoint(ulpath).X {
				llpath = append(llpath, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: sankeyLastPoint(ulpath).X, Y: sankeyLastPoint(llpath).Y}})
			}
			hasLeftInput = true
		}
		tips[i], labelLocations[i] = s.sankeyAddInput(&llpath, angles[i], scaledFlows[i], pathLengths[i])
	}
	hasRightOutput := false
	for i := range flows {
		if angles[i] != sankeyRight || areInputs[i] || !showFlow[i] {
			continue
		}
		if !hasRightOutput {
			if sankeyLastPoint(urpath).X < sankeyLastPoint(lrpath).X {
				urpath = append(urpath, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: sankeyLastPoint(lrpath).X, Y: sankeyLastPoint(urpath).Y}})
			}
			hasRightOutput = true
		}
		tips[i], labelLocations[i] = s.sankeyAddOutput(&urpath, angles[i], scaledFlows[i], pathLengths[i])
	}
	if !hasLeftInput {
		ulpath = sankeyTrimLast(ulpath)
		llpath = sankeyTrimLast(llpath)
	}
	if !hasRightOutput {
		lrpath = sankeyTrimLast(lrpath)
		urpath = sankeyTrimLast(urpath)
	}

	steps := make([]sankeyPathStep, 0, len(urpath)+len(lrpath)+len(llpath)+len(ulpath)+1)
	steps = append(steps, urpath...)
	steps = append(steps, sankeyRevert(lrpath, sankeyLineTo)...)
	steps = append(steps, llpath...)
	steps = append(steps, sankeyRevert(ulpath, sankeyLineTo)...)
	if len(urpath) > 0 {
		steps = append(steps, sankeyPathStep{cmd: sankeyClosePath, pt: urpath[0].pt})
	}

	rotation := cfg.Rotation
	path := sankeyStepsToPath(steps, center, rotation)
	for i := range tips {
		tips[i] = sankeyTransformPoint(tips[i], center, rotation)
		labelLocations[i] = sankeyTransformPoint(labelLocations[i], center, rotation)
	}

	trunkHeight := math.Max(gain, -loss)
	trunk := &Rectangle{
		Patch: Patch{
			FaceColor: render.Color{},
			EdgeColor: edgeColor,
			EdgeWidth: 0,
			z:         2,
		},
		XY:     geom.Pt{X: center.X - trunkLength/2, Y: center.Y - trunkHeight/2},
		Width:  trunkLength,
		Height: trunkHeight,
		Coords: s.opts.Coords,
	}
	extent, haveExtent := sankeyExtent(path.V, labelLocations, showFlow)
	if !haveExtent {
		extent = geom.Rect{Min: center, Max: center}
	}
	diagram := &SankeyDiagram{
		Trunk:  trunk,
		Flows:  append([]float64(nil), flows...),
		Angles: append([]int(nil), angles...),
		Tips:   append([]geom.Pt(nil), tips...),
		Center: center,
		Extent: extent,
	}

	bodyPatch := &PathPatch{
		Patch: Patch{
			FaceColor: patchAlphaColor(defaultFace, alpha),
			EdgeColor: edgeColor,
			EdgeWidth: 1,
			Alpha:     1,
			z:         2.2,
		},
		Path:   path,
		Coords: s.opts.Coords,
	}
	s.ax.AddPatch(bodyPatch)
	diagram.Patch = bodyPatch
	diagram.Ribbons = append(diagram.Ribbons, bodyPatch)

	if cfg.PatchLabel != "" {
		diagram.Text = s.ax.Text(center.X, center.Y, cfg.PatchLabel, TextOptions{
			Coords:   s.opts.Coords,
			FontSize: s.opts.FontSize,
			Color:    s.opts.TextColor,
			HAlign:   TextAlignCenter,
			VAlign:   TextVAlignMiddle,
		})
	}

	labels := sankeyBroadcastStrings(cfg.Labels, len(flows), "")
	for i, flow := range flows {
		if !showFlow[i] || angles[i] == sankeyNone {
			continue
		}
		label := labels[i]
		value := fmt.Sprintf("%g", math.Abs(flow))
		pos := labelLocations[i]
		if label == "" {
			txt := s.ax.Text(pos.X, pos.Y, value, TextOptions{
				Coords:   s.opts.Coords,
				FontSize: s.opts.FontSize,
				Color:    s.opts.TextColor,
				HAlign:   TextAlignCenter,
				VAlign:   TextVAlignMiddle,
			})
			diagram.Values = append(diagram.Values, txt)
			continue
		}
		txt := s.ax.Text(pos.X, pos.Y, label, TextOptions{
			Coords:   s.opts.Coords,
			FontSize: s.opts.FontSize,
			Color:    s.opts.TextColor,
			HAlign:   TextAlignCenter,
			VAlign:   TextVAlignMiddle,
			OffsetY:  -s.opts.FontSize * 0.45,
		})
		diagram.Labels = append(diagram.Labels, txt)
		valueTxt := s.ax.Text(pos.X, pos.Y, value, TextOptions{
			Coords:   s.opts.Coords,
			FontSize: s.opts.FontSize,
			Color:    s.opts.TextColor,
			HAlign:   TextAlignCenter,
			VAlign:   TextVAlignMiddle,
			OffsetY:  s.opts.FontSize * 0.65,
		})
		diagram.Values = append(diagram.Values, valueTxt)
	}

	s.expandExtent(extent)
	s.diagrams = append(s.diagrams, diagram)
	return diagram
}

func sankeyHasVisibleFlow(show []bool) bool {
	for _, visible := range show {
		if visible {
			return true
		}
	}
	return false
}

func sankeyBroadcastInts(values []int, n, fallback int) []int {
	out := make([]int, n)
	for i := range out {
		out[i] = fallback
	}
	if len(values) == 1 {
		for i := range out {
			out[i] = values[0]
		}
		return out
	}
	for i := 0; i < n && i < len(values); i++ {
		out[i] = values[i]
	}
	return out
}

func sankeyBroadcastStrings(values []string, n int, fallback string) []string {
	out := make([]string, n)
	for i := range out {
		out[i] = fallback
	}
	if len(values) == 1 {
		for i := range out {
			out[i] = values[0]
		}
		return out
	}
	for i := 0; i < n && i < len(values); i++ {
		out[i] = values[i]
	}
	return out
}

func sankeyJustifiedPathLengths(base float64, flows []float64, areInputs, show []bool, angles []int) []float64 {
	pathLengths := make([]float64, len(flows))
	for i, angle := range angles {
		if angle == sankeyRight {
			pathLengths[i] = base
		}
	}

	urlength, ullength := base, base
	lrlength, lllength := base, base
	for i, angle := range angles {
		if !show[i] {
			continue
		}
		if angle == sankeyDown && areInputs[i] {
			pathLengths[i] = ullength
			ullength += flows[i]
		} else if angle == sankeyUp && !areInputs[i] {
			pathLengths[i] = urlength
			urlength -= flows[i]
		}
	}
	for i := len(angles) - 1; i >= 0; i-- {
		if !show[i] {
			continue
		}
		if angles[i] == sankeyUp && areInputs[i] {
			pathLengths[i] = lllength
			lllength += flows[i]
		} else if angles[i] == sankeyDown && !areInputs[i] {
			pathLengths[i] = lrlength
			lrlength -= flows[i]
		}
	}
	hasLeftInput := false
	for i := len(angles) - 1; i >= 0; i-- {
		if angles[i] == sankeyRight && areInputs[i] {
			if hasLeftInput {
				pathLengths[i] = 0
			} else {
				hasLeftInput = true
			}
		}
	}
	hasRightOutput := false
	for i, angle := range angles {
		if angle == sankeyRight && !areInputs[i] && show[i] {
			if hasRightOutput {
				pathLengths[i] = 0
			} else {
				hasRightOutput = true
			}
		}
	}
	return pathLengths
}

func sankeyInitialPaths(gap, trunkLength, gain, loss float64) ([]sankeyPathStep, []sankeyPathStep, []sankeyPathStep, []sankeyPathStep) {
	urpath := []sankeyPathStep{
		{cmd: sankeyMoveTo, pt: geom.Pt{X: gap - trunkLength/2, Y: gain / 2}},
		{cmd: sankeyLineTo, pt: geom.Pt{X: (gap - trunkLength/2) / 2, Y: gain / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (gap - trunkLength/2) / 8, Y: gain / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (trunkLength/2 - gap) / 8, Y: -loss / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (trunkLength/2 - gap) / 2, Y: -loss / 2}},
		{cmd: sankeyLineTo, pt: geom.Pt{X: trunkLength/2 - gap, Y: -loss / 2}},
	}
	llpath := []sankeyPathStep{
		{cmd: sankeyLineTo, pt: geom.Pt{X: trunkLength/2 - gap, Y: loss / 2}},
		{cmd: sankeyLineTo, pt: geom.Pt{X: (trunkLength/2 - gap) / 2, Y: loss / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (trunkLength/2 - gap) / 8, Y: loss / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (gap - trunkLength/2) / 8, Y: -gain / 2}},
		{cmd: sankeyCurveTo, pt: geom.Pt{X: (gap - trunkLength/2) / 2, Y: -gain / 2}},
		{cmd: sankeyLineTo, pt: geom.Pt{X: gap - trunkLength/2, Y: -gain / 2}},
	}
	lrpath := []sankeyPathStep{
		{cmd: sankeyLineTo, pt: geom.Pt{X: trunkLength/2 - gap, Y: loss / 2}},
	}
	ulpath := []sankeyPathStep{
		{cmd: sankeyLineTo, pt: geom.Pt{X: gap - trunkLength/2, Y: gain / 2}},
	}
	return urpath, llpath, lrpath, ulpath
}

func (s *Sankey) sankeyAddInput(path *[]sankeyPathStep, angle int, flow, length float64) (geom.Pt, geom.Pt) {
	if angle == sankeyNone {
		return geom.Pt{}, geom.Pt{}
	}
	x, y := sankeyLastPoint(*path).X, sankeyLastPoint(*path).Y
	dipDepth := flow / 2 * s.pitch
	if angle == sankeyRight {
		x -= length
		dip := geom.Pt{X: x + dipDepth, Y: y + flow/2}
		*path = append(*path,
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y}},
			sankeyPathStep{cmd: sankeyLineTo, pt: dip},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y + flow}},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x + s.opts.Gap, Y: y + flow}},
		)
		return dip, geom.Pt{X: dip.X - s.opts.Offset, Y: dip.Y}
	}

	x -= s.opts.Gap
	sign := -1.0
	quadrant := 2
	if angle == sankeyUp {
		sign = 1
		quadrant = 1
	}
	dip := geom.Pt{X: x - flow/2, Y: y - sign*(length-dipDepth)}
	if s.opts.Radius != 0 {
		*path = append(*path, sankeyArc(quadrant, angle == sankeyUp, s.opts.Radius, geom.Pt{X: x + s.opts.Radius, Y: y - sign*s.opts.Radius})...)
	} else {
		*path = append(*path, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y}})
	}
	*path = append(*path,
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y - sign*length}},
		sankeyPathStep{cmd: sankeyLineTo, pt: dip},
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - flow, Y: y - sign*length}},
	)
	*path = append(*path, sankeyArc(quadrant, angle == sankeyDown, flow+s.opts.Radius, geom.Pt{X: x + s.opts.Radius, Y: y - sign*s.opts.Radius})...)
	*path = append(*path, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - flow, Y: y + sign*flow}})
	return dip, geom.Pt{X: dip.X, Y: dip.Y - sign*s.opts.Offset}
}

func (s *Sankey) sankeyAddOutput(path *[]sankeyPathStep, angle int, flow, length float64) (geom.Pt, geom.Pt) {
	if angle == sankeyNone {
		return geom.Pt{}, geom.Pt{}
	}
	x, y := sankeyLastPoint(*path).X, sankeyLastPoint(*path).Y
	tipHeight := (s.opts.Shoulder - flow/2) * s.pitch
	if angle == sankeyRight {
		x += length
		tip := geom.Pt{X: x + tipHeight, Y: y + flow/2}
		*path = append(*path,
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y}},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y + s.opts.Shoulder}},
			sankeyPathStep{cmd: sankeyLineTo, pt: tip},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y - s.opts.Shoulder + flow}},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y + flow}},
			sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - s.opts.Gap, Y: y + flow}},
		)
		return tip, geom.Pt{X: tip.X + s.opts.Offset, Y: tip.Y}
	}

	x += s.opts.Gap
	sign := -1.0
	quadrant := 0
	if angle == sankeyUp {
		sign = 1
		quadrant = 3
	}
	tip := geom.Pt{X: x - flow/2, Y: y + sign*(length+tipHeight)}
	if s.opts.Radius != 0 {
		*path = append(*path, sankeyArc(quadrant, angle == sankeyUp, s.opts.Radius, geom.Pt{X: x - s.opts.Radius, Y: y + sign*s.opts.Radius})...)
	} else {
		*path = append(*path, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y}})
	}
	*path = append(*path,
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x, Y: y + sign*length}},
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - s.opts.Shoulder, Y: y + sign*length}},
		sankeyPathStep{cmd: sankeyLineTo, pt: tip},
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x + s.opts.Shoulder - flow, Y: y + sign*length}},
		sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - flow, Y: y + sign*length}},
	)
	*path = append(*path, sankeyArc(quadrant, angle == sankeyDown, s.opts.Radius-flow, geom.Pt{X: x - s.opts.Radius, Y: y + sign*s.opts.Radius})...)
	*path = append(*path, sankeyPathStep{cmd: sankeyLineTo, pt: geom.Pt{X: x - flow, Y: y + sign*flow}})
	return tip, geom.Pt{X: tip.X, Y: tip.Y + sign*s.opts.Offset}
}

func sankeyArc(quadrant int, cw bool, radius float64, center geom.Pt) []sankeyPathStep {
	base := []geom.Pt{
		{X: 1, Y: 0},
		{X: 1, Y: 0.265114773},
		{X: 0.894571235, Y: 0.519642327},
		{X: 0.707106781, Y: 0.707106781},
		{X: 0.519642327, Y: 0.894571235},
		{X: 0.265114773, Y: 1},
		{X: 0, Y: 1},
	}
	pts := make([]geom.Pt, len(base))
	for i, pt := range base {
		switch quadrant {
		case 0, 2:
			if cw {
				pts[i] = pt
			} else {
				pts[i] = geom.Pt{X: pt.Y, Y: pt.X}
			}
		default:
			if cw {
				pts[i] = geom.Pt{X: -pt.Y, Y: pt.X}
			} else {
				pts[i] = geom.Pt{X: -pt.X, Y: pt.Y}
			}
		}
		if quadrant > 1 {
			pts[i].X *= -radius
			pts[i].Y *= -radius
		} else {
			pts[i].X *= radius
			pts[i].Y *= radius
		}
		pts[i].X += center.X
		pts[i].Y += center.Y
	}
	out := make([]sankeyPathStep, len(pts))
	for i, pt := range pts {
		cmd := sankeyCurveTo
		if i == 0 {
			cmd = sankeyLineTo
		}
		out[i] = sankeyPathStep{cmd: cmd, pt: pt}
	}
	return out
}

func sankeyRevert(path []sankeyPathStep, first sankeyPathCmd) []sankeyPathStep {
	out := make([]sankeyPathStep, 0, len(path))
	next := first
	for i := len(path) - 1; i >= 0; i-- {
		out = append(out, sankeyPathStep{cmd: next, pt: path[i].pt})
		next = path[i].cmd
	}
	return out
}

func sankeyStepsToPath(steps []sankeyPathStep, center geom.Pt, rotation float64) geom.Path {
	var path geom.Path
	curves := make([]geom.Pt, 0, 3)
	flushCurve := func() {
		for len(curves) >= 3 {
			path.CubicTo(curves[0], curves[1], curves[2])
			curves = curves[3:]
		}
	}
	for _, step := range steps {
		pt := sankeyTransformPoint(step.pt, center, rotation)
		switch step.cmd {
		case sankeyMoveTo:
			flushCurve()
			path.MoveTo(pt)
		case sankeyLineTo:
			flushCurve()
			path.LineTo(pt)
		case sankeyCurveTo:
			curves = append(curves, pt)
			if len(curves) == 3 {
				flushCurve()
			}
		case sankeyClosePath:
			flushCurve()
			path.Close()
		}
	}
	flushCurve()
	return path
}

func sankeyTransformPoint(pt, center geom.Pt, rotation float64) geom.Pt {
	if rotation != 0 {
		rad := rotation * math.Pi / 180
		cosv, sinv := math.Cos(rad), math.Sin(rad)
		pt = geom.Pt{
			X: pt.X*cosv - pt.Y*sinv,
			Y: pt.X*sinv + pt.Y*cosv,
		}
	}
	return geom.Pt{X: pt.X + center.X, Y: pt.Y + center.Y}
}

func sankeyTrimLast(path []sankeyPathStep) []sankeyPathStep {
	if len(path) == 0 {
		return path
	}
	return path[:len(path)-1]
}

func sankeyLastPoint(path []sankeyPathStep) geom.Pt {
	if len(path) == 0 {
		return geom.Pt{}
	}
	return path[len(path)-1].pt
}

func sankeyExtent(vertices, labels []geom.Pt, show []bool) (geom.Rect, bool) {
	var rect geom.Rect
	have := false
	add := func(pt geom.Pt) {
		if math.IsNaN(pt.X) || math.IsNaN(pt.Y) || math.IsInf(pt.X, 0) || math.IsInf(pt.Y, 0) {
			return
		}
		if !have {
			rect = geom.Rect{Min: pt, Max: pt}
			have = true
			return
		}
		rect = expandRect(rect, pt)
	}
	for _, pt := range vertices {
		add(pt)
	}
	for i, pt := range labels {
		if i < len(show) && show[i] {
			add(pt)
		}
	}
	return rect, have
}

func (s *Sankey) expandExtent(rect geom.Rect) {
	if s == nil {
		return
	}
	if !s.haveExtent {
		s.extent = rect
		s.haveExtent = true
		return
	}
	s.extent = unionRect(s.extent, rect)
}

// Finish returns all diagrams added through the builder and applies Matplotlib's
// final Sankey axes limits/aspect adjustment for data-coordinate diagrams.
func (s *Sankey) Finish() []*SankeyDiagram {
	if s == nil {
		return nil
	}
	if s.ax != nil && s.haveExtent && isDataCoords(s.opts.Coords) {
		margin := s.opts.Margin
		s.ax.SetXLim(s.extent.Min.X-margin, s.extent.Max.X+margin)
		s.ax.SetYLim(s.extent.Min.Y-margin, s.extent.Max.Y+margin)
		_ = s.ax.SetAspect("equal")
	}
	return append([]*SankeyDiagram(nil), s.diagrams...)
}

// NewSankey creates a Matplotlib-style Sankey builder for one axes.
func NewSankey(ax *Axes, opts ...SankeyOptions) *Sankey {
	if ax == nil {
		return nil
	}
	cfg := SankeyOptions{
		Center:      geom.Pt{},
		Coords:      Coords(CoordData),
		Scale:       1,
		TrunkLength: 1,
		PathLength:  0.25,
		Gap:         0.25,
		Radius:      0.1,
		Shoulder:    0.03,
		Offset:      0.15,
		HeadAngle:   100,
		Margin:      0.4,
		Tolerance:   1e-6,
		Alpha:       1,
		TextColor:   ax.resolvedRC().DefaultTextColor(),
		FontSize:    ax.resolvedRC().FontSize,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.Scale <= 0 {
			cfg.Scale = 1
		}
		if cfg.TrunkLength <= 0 {
			cfg.TrunkLength = 1
		}
		if cfg.PathLength <= 0 {
			cfg.PathLength = 0.25
		}
		if cfg.Gap <= 0 {
			cfg.Gap = 0.25
		}
		if cfg.Radius <= 0 {
			cfg.Radius = 0.1
		}
		if cfg.Shoulder <= 0 {
			cfg.Shoulder = 0.03
		}
		if cfg.Offset <= 0 {
			cfg.Offset = 0.15
		}
		if cfg.HeadAngle <= 0 {
			cfg.HeadAngle = 100
		}
		if cfg.Margin <= 0 {
			cfg.Margin = 0.4
		}
		if cfg.Tolerance <= 0 {
			cfg.Tolerance = 1e-6
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.FontSize <= 0 {
			cfg.FontSize = ax.resolvedRC().FontSize
		}
		if cfg.TextColor == (render.Color{}) {
			cfg.TextColor = ax.resolvedRC().DefaultTextColor()
		}
	}
	pitch := math.Tan(math.Pi * (1 - cfg.HeadAngle/180) / 2)
	return &Sankey{
		ax:     ax,
		opts:   cfg,
		cursor: cfg.Center,
		pitch:  pitch,
	}
}

// Eventplot adds a collection of short event markers to the axes.
func (a *Axes) Eventplot(positions [][]float64, opts ...EventPlotOptions) *EventCollection {
	if a == nil || len(positions) == 0 {
		return nil
	}
	cfg := EventPlotOptions{
		Orientation: EventOrientationVertical,
		LineWidth:   1.5,
		Alpha:       1,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1.5
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
	}

	offsets := cfg.LineOffsets
	if len(offsets) == 0 {
		offsets = make([]float64, len(positions))
		for i := range offsets {
			offsets[i] = float64(i + 1)
		}
	}
	lengths := cfg.LineLengths
	if len(lengths) == 0 {
		lengths = make([]float64, len(positions))
		for i := range lengths {
			lengths[i] = 0.8
		}
	}

	segments := make([][]geom.Pt, 0)
	colors := make([]render.Color, 0)
	for i, group := range positions {
		offset := floatAt(offsets, i, float64(i+1))
		length := math.Abs(floatAt(lengths, i, 0.8))
		half := length / 2
		col := colorAt(a.NextColor(), cfg.Colors, i)
		col.A *= clampOneToOne(cfg.Alpha)
		for _, value := range group {
			if !isFinite(value) {
				continue
			}
			segment := []geom.Pt{
				{X: value, Y: offset - half},
				{X: value, Y: offset + half},
			}
			if cfg.Orientation == EventOrientationHorizontal {
				segment = []geom.Pt{
					{X: offset - half, Y: value},
					{X: offset + half, Y: value},
				}
			}
			segments = append(segments, segment)
			colors = append(colors, col)
		}
	}
	if len(segments) == 0 {
		return nil
	}

	collection := &EventCollection{
		LineCollection: LineCollection{
			Collection: Collection{Label: cfg.Label, Alpha: 1, z: 2},
			Segments:   segments,
			Colors:     colors,
			LineWidth:  cfg.LineWidth,
			LineCap:    render.CapButt,
			LineJoin:   render.JoinRound,
		},
		Positions:   positions,
		Orientation: cfg.Orientation,
		LineOffsets: append([]float64(nil), offsets...),
		LineLengths: append([]float64(nil), lengths...),
	}
	a.AddCollection(collection)
	return collection
}

// Hexbin bins points into a staggered hexagonal grid and colors occupied bins by aggregate value.
func (a *Axes) Hexbin(x, y []float64, opts ...HexbinOptions) *HexbinCollection {
	if a == nil || len(x) == 0 || len(y) == 0 {
		return nil
	}

	n := min(len(x), len(y))
	cfg := HexbinOptions{
		GridSizeX: 18,
		MinCount:  1,
		Colormap:  "viridis",
		Alpha:     1,
		LineWidth: 0.75,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.GridSizeX <= 0 {
			cfg.GridSizeX = 18
		}
		if cfg.MinCount <= 0 {
			cfg.MinCount = 1
		}
		if cfg.Colormap == "" {
			cfg.Colormap = "viridis"
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 0.75
		}
	}
	xscale := normalizeHexScale(cfg.XScale)
	yscale := normalizeHexScale(cfg.YScale)

	extent := cfg.Extent
	if extent == nil {
		tx, ty := specialtyHexbinScaledPoints(x[:n], y[:n], xscale, yscale)
		rect := finitePointRect(tx, ty)
		extent = &rect
	}
	if extent.W() == 0 {
		extent.Max.X = extent.Min.X + 1
	}
	if extent.H() == 0 {
		extent.Max.Y = extent.Min.Y + 1
	}

	gridX := max(1, cfg.GridSizeX)
	gridY := cfg.GridSizeY
	if gridY <= 0 {
		gridY = max(1, int(float64(gridX)/math.Sqrt(3)))
	}

	xMin, xMax := extent.Min.X, extent.Max.X
	yMin, yMax := extent.Min.Y, extent.Max.Y
	padding := 1e-9 * (xMax - xMin)
	xMin -= padding
	xMax += padding

	xStep := (xMax - xMin) / float64(gridX)
	yStep := (yMax - yMin) / float64(gridY)
	if xStep <= 0 {
		xStep = 1
	}
	if yStep <= 0 {
		yStep = 1
	}

	bins := map[hexbinKey]*hexbinBin{}
	for i := range n {
		xi, yi := specialtyHexbinScaledPoint(x[i], y[i], xscale, yscale)
		if !isFinite(xi) || !isFinite(yi) {
			continue
		}
		k, center, ok := matplotlibHexbinCenter(xi, yi, xMin, yMin, gridX, gridY, xStep, yStep)
		if !ok {
			continue
		}
		entry := bins[k]
		if entry == nil {
			entry = &hexbinBin{
				center: center,
			}
			bins[k] = entry
		}
		entry.count++
		if i < len(cfg.C) && isFinite(cfg.C[i]) {
			entry.sum += cfg.C[i]
			entry.values = append(entry.values, cfg.C[i])
		} else {
			entry.sum += 1
		}
	}
	if len(bins) == 0 {
		return nil
	}

	keys := make([]hexbinKey, 0, len(bins))
	for k := range bins {
		keys = append(keys, k)
	}
	slices.SortFunc(keys, func(a, b hexbinKey) int {
		if a.lattice != b.lattice {
			return a.lattice - b.lattice
		}
		if a.row != b.row {
			return a.row - b.row
		}
		return a.col - b.col
	})

	polygons := make([][]geom.Pt, 0, len(keys))
	values := make([]float64, 0, len(keys))
	counts := make([]float64, 0, len(keys))
	centers := make([]geom.Pt, 0, len(keys))
	rx := xStep / 2
	ry := yStep / 3
	for _, k := range keys {
		entry := bins[k]
		if int(entry.count) < cfg.MinCount {
			continue
		}
		value := entry.count
		if len(cfg.C) > 0 {
			value = reduceHexbinValues(entry, cfg.Reduce)
		}
		center := specialtyHexbinUnscalePoint(entry.center, xscale, yscale)
		scaledPolygon := specialtyHexagon(entry.center, rx, ry)
		polygon := make([]geom.Pt, len(scaledPolygon))
		for i, pt := range scaledPolygon {
			polygon[i] = specialtyHexbinUnscalePoint(pt, xscale, yscale)
		}
		polygons = append(polygons, polygon)
		values = append(values, value)
		counts = append(counts, entry.count)
		centers = append(centers, center)
	}
	if len(polygons) == 0 {
		return nil
	}
	values = applyHexbinBins(values, cfg)
	norm := cfg.Norm
	if strings.EqualFold(cfg.Bins, "log") && norm == nil {
		norm = LogNorm{VMin: math.NaN(), VMax: math.NaN()}
	}

	mapping, err := ResolveScalarMapValues(values, ScalarMapConfig{
		Colormap: cfg.Colormap,
		Norm:     norm,
		VMin:     cfg.VMin,
		VMax:     cfg.VMax,
	})
	if err != nil {
		return nil
	}
	faceColors := make([]render.Color, len(values))
	for i, value := range values {
		faceColors[i] = mapping.Color(value, cfg.Alpha)
	}
	edgeColor := render.Color{R: 1, G: 1, B: 1, A: 0.9}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}
	edgeColors := faceColors
	if cfg.EdgeColor != nil {
		edgeColors = nil
	}
	collection := &HexbinCollection{
		PolyCollection: PolyCollection{
			PatchCollection: PatchCollection{
				Collection: Collection{
					Label:    cfg.Label,
					Alpha:    1,
					Colormap: mapping.Colormap,
					Norm:     mapping.Norm,
					VMin:     mapping.VMin,
					VMax:     mapping.VMax,
					z:        2,
				},
				FaceColors: faceColors,
				EdgeColor:  edgeColor,
				EdgeColors: edgeColors,
				EdgeWidth:  cfg.LineWidth,
			},
			Polygons: polygons,
		},
		BinCenters: centers,
		Values:     values,
		Counts:     counts,
	}
	if cfg.Marginals {
		collection.HBar, collection.VBar = specialtyHexbinMarginals(x[:n], y[:n], cfg, mapping)
		if collection.HBar != nil {
			a.AddCollection(collection.HBar)
		}
		if collection.VBar != nil {
			a.AddCollection(collection.VBar)
		}
	}
	a.AddCollection(collection)
	if xscale == "log" {
		_ = a.SetXScale("log")
	}
	if yscale == "log" {
		_ = a.SetYScale("log")
	}
	return collection
}

// Pie draws pie-slice wedges and returns the artists grouped in a container.
func (a *Axes) Pie(values []float64, opts ...PieOptions) *PieContainer {
	if a == nil || len(values) == 0 {
		return nil
	}
	cfg := PieOptions{
		Center:        geom.Pt{},
		Radius:        1,
		StartAngle:    0,
		LabelDistance: 1.15,
		PctDistance:   0.62,
		LineWidth:     1,
		Alpha:         1,
		Coords:        Coords(CoordData),
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.Radius <= 0 {
			cfg.Radius = 1
		}
		if cfg.LabelDistance <= 0 {
			cfg.LabelDistance = 1.15
		}
		if cfg.PctDistance <= 0 {
			cfg.PctDistance = 0.62
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordData)
		}
	}

	total := 0.0
	filtered := make([]float64, len(values))
	for i, value := range values {
		if value >= 0 && isFinite(value) {
			filtered[i] = value
			total += value
		}
	}
	if total == 0 {
		return nil
	}
	normalize := specialtyBool(cfg.Normalize, true)
	if !normalize && total > 1 {
		return nil
	}

	container := &PieContainer{}
	edgeColor := render.Color{R: 1, G: 1, B: 1, A: 1}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}

	theta := cfg.StartAngle
	counterClockwise := specialtyBool(cfg.CounterClockwise, true)
	for i, value := range filtered {
		if value <= 0 {
			continue
		}
		fraction := value
		if normalize {
			fraction = value / total
		}
		span := fraction * 360
		end := theta + span
		if !counterClockwise {
			end = theta - span
		}
		mid := (theta + end) / 2
		explode := floatAt(cfg.Explode, i, 0)
		offset := geom.Pt{
			X: math.Cos(mid*math.Pi/180) * cfg.Radius * explode,
			Y: math.Sin(mid*math.Pi/180) * cfg.Radius * explode,
		}
		color := colorAt(a.NextColor(), cfg.Colors, i)
		color.A *= clampOneToOne(cfg.Alpha)
		hatchColor := cfg.HatchColor
		if hatchColor == (render.Color{}) {
			hatchColor = edgeColor
		}
		hatchWidth := cfg.HatchWidth
		if hatchWidth <= 0 {
			hatchWidth = 1
		}
		if cfg.Shadow {
			shadowOffset := cfg.ShadowOffset
			if shadowOffset == (geom.Pt{}) {
				shadowOffset = geom.Pt{X: -0.02 * cfg.Radius, Y: -0.02 * cfg.Radius}
			}
			shadowColor := cfg.ShadowColor
			if shadowColor == (render.Color{}) {
				shadowColor = render.Color{R: 0, G: 0, B: 0, A: 0.25}
			}
			shadow := &Wedge{
				Patch: Patch{
					FaceColor: shadowColor,
					EdgeColor: render.Color{},
					Alpha:     1,
					Label:     "_nolegend_",
					z:         1.8,
				},
				Center: geom.Pt{X: cfg.Center.X + offset.X + shadowOffset.X, Y: cfg.Center.Y + offset.Y + shadowOffset.Y},
				Radius: cfg.Radius,
				Width:  cfg.Width,
				Theta1: theta,
				Theta2: end,
				Coords: cfg.Coords,
			}
			a.AddPatch(shadow)
			container.Shadows = append(container.Shadows, shadow)
		}
		wedge := &Wedge{
			Patch: Patch{
				FaceColor:  color,
				EdgeColor:  edgeColor,
				EdgeWidth:  cfg.LineWidth,
				Alpha:      1,
				Label:      stringAt("", cfg.Labels, i),
				Hatch:      stringAt(cfg.Hatch, cfg.Hatches, i),
				HatchColor: hatchColor,
				HatchWidth: hatchWidth,
				z:          2,
			},
			Center: geom.Pt{X: cfg.Center.X + offset.X, Y: cfg.Center.Y + offset.Y},
			Radius: cfg.Radius,
			Width:  cfg.Width,
			Theta1: theta,
			Theta2: end,
			Coords: cfg.Coords,
		}
		a.AddPatch(wedge)
		container.Wedges = append(container.Wedges, wedge)

		if label := stringAt("", cfg.Labels, i); label != "" {
			labelPt := piePoint(wedge.Center, cfg.Radius*cfg.LabelDistance, mid)
			clipOn := false
			container.LabelAngles = append(container.LabelAngles, pieLabelRotation(mid, cfg.RotateLabels))
			container.Labels = append(container.Labels, a.Text(labelPt.X, labelPt.Y, label, TextOptions{
				Coords: cfg.Coords,
				HAlign: pieAlign(mid),
				VAlign: TextVAlignMiddle,
				Angle:  pieLabelRotation(mid, cfg.RotateLabels),
				ClipOn: &clipOn,
			}))
		}
		if cfg.AutoPct != "" {
			autoPt := piePoint(wedge.Center, cfg.Radius*cfg.PctDistance, mid)
			autoText := fmt.Sprintf(cfg.AutoPct, fraction*100)
			clipOn := false
			container.AutoText = append(container.AutoText, a.Text(autoPt.X, autoPt.Y, autoText, TextOptions{
				Coords: cfg.Coords,
				HAlign: TextAlignCenter,
				VAlign: TextVAlignMiddle,
				ClipOn: &clipOn,
			}))
		}

		theta = end
	}

	if cfg.Coords == Coords(CoordData) {
		padding := cfg.Radius * 1.25
		a.SetXLim(cfg.Center.X-padding, cfg.Center.X+padding)
		a.SetYLim(cfg.Center.Y-padding, cfg.Center.Y+padding)
		a.SetAxisEqual()
		if !specialtyBool(cfg.Frame, false) {
			hideAxesFrame(a)
		}
	}
	return container
}

// PieLabel adds labels to an existing pie container, mirroring Matplotlib's pie_label helper.
func (a *Axes) PieLabel(container *PieContainer, labels []string, opts ...PieLabelOptions) []*Text {
	if a == nil || container == nil || len(container.Wedges) == 0 {
		return nil
	}
	cfg := PieLabelOptions{
		Distance:  0.6,
		Alignment: "auto",
		Coords:    Coords(CoordData),
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.Distance <= 0 {
			cfg.Distance = 0.6
		}
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordData)
		}
	}
	out := make([]*Text, 0, len(container.Wedges))
	for i, wedge := range container.Wedges {
		if wedge == nil {
			continue
		}
		label := stringAt("", labels, i)
		if label == "" {
			continue
		}
		mid := (wedge.Theta1 + wedge.Theta2) / 2
		pt := piePoint(wedge.Center, wedge.Radius*cfg.Distance, mid)
		clipOn := false
		align := pieAlign(mid)
		if strings.EqualFold(cfg.Alignment, "center") {
			align = TextAlignCenter
		}
		txt := a.Text(pt.X, pt.Y, label, TextOptions{
			Coords: cfg.Coords,
			HAlign: align,
			VAlign: TextVAlignMiddle,
			Angle:  pieLabelRotation(mid, cfg.Rotate),
			ClipOn: &clipOn,
		})
		out = append(out, txt)
		container.Labels = append(container.Labels, txt)
		container.LabelAngles = append(container.LabelAngles, pieLabelRotation(mid, cfg.Rotate))
	}
	return out
}

// Violinplot draws one violin body per dataset and optional summary lines.
func (a *Axes) Violinplot(data [][]float64, opts ...ViolinOptions) *ViolinContainer {
	if a == nil || len(data) == 0 {
		return nil
	}
	cfg := ViolinOptions{
		EdgeWidth: 1,
		Alpha:     0.65,
		Points:    100,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.EdgeWidth <= 0 {
			cfg.EdgeWidth = 1
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 0.65
		}
		if cfg.Points < 8 {
			cfg.Points = 100
		}
	}

	polygons := make([][]geom.Pt, 0, len(data))
	faceColors := make([]render.Color, 0, len(data))
	medianSegments := make([][]geom.Pt, 0, len(data))
	meanSegments := make([][]geom.Pt, 0, len(data))
	extremaSegments := make([][]geom.Pt, 0, len(data)*3)
	quantileSegments := make([][]geom.Pt, 0, len(data))
	orientation := normalizeViolinOrientation(cfg.Orientation)
	side := normalizeViolinSide(cfg.Side)

	for i, series := range data {
		values := specialtyFiniteValues(series)
		if len(values) == 0 {
			continue
		}

		width := math.Abs(floatAt(cfg.Widths, i, 0.5))
		if width == 0 {
			width = 0.5
		}
		position := floatAt(cfg.Positions, i, float64(i+1))
		stats := specialtyViolinStats(values)
		grid, density := specialtyKDE(values, cfg.Points, cfg.Bandwidth, cfg.BandwidthMethod)
		if len(grid) == 0 || len(density) == 0 {
			continue
		}

		maxDensity := 0.0
		for _, d := range density {
			if d > maxDensity {
				maxDensity = d
			}
		}
		if maxDensity == 0 {
			maxDensity = 1
		}

		lowSide := make([]geom.Pt, 0, len(grid))
		highSide := make([]geom.Pt, 0, len(grid))
		for j := range grid {
			halfWidth := density[j] / maxDensity * width * 0.5
			lowOffset := -halfWidth
			highOffset := halfWidth
			switch side {
			case "high":
				lowOffset = 0
			case "low":
				highOffset = 0
			}
			lowSide = append(lowSide, violinPoint(position+lowOffset, grid[j], orientation))
			highSide = append(highSide, violinPoint(position+highOffset, grid[j], orientation))
		}
		polygon := make([]geom.Pt, 0, len(lowSide)+len(highSide))
		polygon = append(polygon, lowSide...)
		for j := len(highSide) - 1; j >= 0; j-- {
			polygon = append(polygon, highSide[j])
		}
		polygons = append(polygons, polygon)

		color := colorAt(a.NextColor(), cfg.Colors, i)
		color.A *= clampOneToOne(cfg.Alpha)
		faceColors = append(faceColors, color)

		if specialtyBool(cfg.ShowMeans, false) {
			meanSegments = append(meanSegments, violinPerpSegment(position, width, stats.mean, orientation, side))
		}
		if specialtyBool(cfg.ShowMedians, true) {
			medianSegments = append(medianSegments, violinPerpSegment(position, width*1.2, stats.median, orientation, side))
		}
		for _, q := range violinQuantiles(cfg.Quantiles, i, values) {
			quantileSegments = append(quantileSegments, violinPerpSegment(position, width, q, orientation, side))
		}
		if specialtyBool(cfg.ShowExtrema, true) {
			extremaSegments = append(extremaSegments,
				violinParallelSegment(position, stats.min, stats.max, orientation),
				violinPerpSegment(position, width, stats.min, orientation, side),
				violinPerpSegment(position, width, stats.max, orientation, side),
			)
		}
	}

	if len(polygons) == 0 {
		return nil
	}

	edgeColor := render.Color{R: 0.12, G: 0.12, B: 0.12, A: 0.9}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}
	lineColor := edgeColor
	if cfg.LineColor != nil {
		lineColor = *cfg.LineColor
	}

	container := &ViolinContainer{
		Bodies: &PolyCollection{
			PatchCollection: PatchCollection{
				Collection: Collection{Label: cfg.Label, Alpha: 1, z: 2},
				FaceColors: faceColors,
				EdgeColor:  edgeColor,
				EdgeWidth:  cfg.EdgeWidth,
			},
			Polygons: polygons,
		},
	}
	a.AddCollection(container.Bodies)

	if len(meanSegments) > 0 {
		container.Means = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.3},
			Segments:   meanSegments,
			Color:      lineColor,
			LineWidth:  math.Max(cfg.EdgeWidth, 1.25),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Means)
	}
	if len(medianSegments) > 0 {
		container.Medians = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.35},
			Segments:   medianSegments,
			Color:      render.Color{R: 1, G: 1, B: 1, A: 0.95},
			LineWidth:  math.Max(cfg.EdgeWidth, 1.5),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Medians)
	}
	if len(quantileSegments) > 0 {
		container.Quantiles = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.32},
			Segments:   quantileSegments,
			Color:      lineColor,
			LineWidth:  math.Max(cfg.EdgeWidth, 1.25),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Quantiles)
	}
	if len(extremaSegments) > 0 {
		container.Extrema = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.1},
			Segments:   extremaSegments,
			Color:      lineColor,
			LineWidth:  math.Max(cfg.EdgeWidth*0.9, 1),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Extrema)
	}
	return container
}

// Table adds a simple table artist positioned in axes coordinates by default.
func (a *Axes) Table(opts ...TableOptions) *Table {
	if a == nil {
		return nil
	}
	cfg := TableOptions{
		BBox:            geom.Rect{Min: geom.Pt{X: 0, Y: 0}, Max: geom.Pt{X: 1, Y: 1}},
		Coords:          Coords(CoordAxes),
		FontSize:        a.resolvedRC().FontSize,
		TextColor:       a.resolvedRC().DefaultTextColor(),
		HeaderTextColor: a.resolvedRC().DefaultTextColor(),
		HeaderFillColor: render.Color{R: 1, G: 1, B: 1, A: 1},
		CellFillColor:   render.Color{R: 1, G: 1, B: 1, A: 1},
		EdgeColor:       render.Color{R: 0, G: 0, B: 0, A: 1},
		LineWidth:       1,
		CellLoc:         "right",
		RowLoc:          "left",
		ColLoc:          "center",
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.BBox == (geom.Rect{}) {
			cfg.BBox = geom.Rect{Min: geom.Pt{X: 0, Y: 0}, Max: geom.Pt{X: 1, Y: 1}}
		}
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordAxes)
		}
		if cfg.FontSize <= 0 {
			cfg.FontSize = a.resolvedRC().FontSize
		}
		if cfg.TextColor == (render.Color{}) {
			cfg.TextColor = a.resolvedRC().DefaultTextColor()
		}
		if cfg.HeaderTextColor == (render.Color{}) {
			cfg.HeaderTextColor = a.resolvedRC().DefaultTextColor()
		}
		if cfg.HeaderFillColor == (render.Color{}) {
			cfg.HeaderFillColor = render.Color{R: 1, G: 1, B: 1, A: 1}
		}
		if cfg.CellFillColor == (render.Color{}) {
			cfg.CellFillColor = render.Color{R: 1, G: 1, B: 1, A: 1}
		}
		if cfg.EdgeColor == (render.Color{}) {
			cfg.EdgeColor = render.Color{R: 0, G: 0, B: 0, A: 1}
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1
		}
		if cfg.CellLoc == "" {
			cfg.CellLoc = "right"
		}
		if cfg.RowLoc == "" {
			cfg.RowLoc = "left"
		}
		if cfg.ColLoc == "" {
			cfg.ColLoc = "center"
		}
	}

	rows := len(cfg.CellText)
	cols := 0
	for _, row := range cfg.CellText {
		cols = max(cols, len(row))
	}
	if rows == 0 && len(cfg.RowLabels) == 0 && len(cfg.ColLabels) == 0 {
		return nil
	}
	if cols == 0 {
		cols = 1
	}

	hasRowLabels := len(cfg.RowLabels) > 0
	hasColLabels := len(cfg.ColLabels) > 0
	gridRows := rows
	if hasColLabels {
		gridRows++
	}
	gridCols := cols + boolOffset(hasRowLabels)
	dataCellW := cfg.BBox.W() / float64(cols)
	rowLabelW := 0.0
	if hasRowLabels {
		rowLabelW = tableRowLabelWidth(cfg.RowLabels, dataCellW)
	}
	cellH := cfg.BBox.H() / float64(gridRows)
	cellAlign := tableTextAlign(cfg.CellLoc, TextAlignRight)
	rowAlign := tableTextAlign(cfg.RowLoc, TextAlignLeft)
	colAlign := tableTextAlign(cfg.ColLoc, TextAlignCenter)

	cells := make([][]tableCell, gridRows)
	for r := range gridRows {
		cells[r] = make([]tableCell, gridCols)
		for c := range gridCols {
			cells[r][c] = tableCell{
				Fill:   cfg.CellFillColor,
				Rect:   tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, r, c),
				HAlign: cellAlign,
			}
		}
	}
	if hasColLabels {
		for c := 0; c < cols; c++ {
			col := c + boolOffset(hasRowLabels)
			cells[0][col] = tableCell{
				Text:     stringAt("", cfg.ColLabels, c),
				Fill:     cfg.HeaderFillColor,
				IsHeader: true,
				Rect:     tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, 0, col),
				HAlign:   colAlign,
			}
		}
	}
	if hasRowLabels {
		for r := 0; r < rows; r++ {
			row := r + boolOffset(hasColLabels)
			cells[row][0] = tableCell{
				Text:     stringAt("", cfg.RowLabels, r),
				Fill:     cfg.HeaderFillColor,
				IsHeader: true,
				Rect: geom.Rect{
					Min: geom.Pt{X: cfg.BBox.Min.X - rowLabelW, Y: cfg.BBox.Max.Y - float64(row+1)*cellH},
					Max: geom.Pt{X: cfg.BBox.Min.X, Y: cfg.BBox.Max.Y - float64(row)*cellH},
				},
				HAlign: rowAlign,
			}
		}
	}
	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			fill := cfg.CellFillColor
			if r < len(cfg.CellColors) && c < len(cfg.CellColors[r]) && cfg.CellColors[r][c] != (render.Color{}) {
				fill = cfg.CellColors[r][c]
			}
			row := r + boolOffset(hasColLabels)
			col := c + boolOffset(hasRowLabels)
			cells[row][col] = tableCell{
				Text:   stringAt("", cfg.CellText[r], c),
				Fill:   fill,
				Rect:   tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, row, col),
				HAlign: cellAlign,
			}
		}
	}

	table := &Table{
		Cells:           cells,
		BBox:            cfg.BBox,
		Coords:          cfg.Coords,
		FontSize:        cfg.FontSize,
		TextColor:       cfg.TextColor,
		HeaderTextColor: cfg.HeaderTextColor,
		EdgeColor:       cfg.EdgeColor,
		LineWidth:       cfg.LineWidth,
		z:               4,
	}
	a.Add(table)
	return table
}

func tableTextAlign(loc string, fallback TextAlign) TextAlign {
	switch strings.ToLower(strings.TrimSpace(loc)) {
	case "left":
		return TextAlignLeft
	case "center", "centre":
		return TextAlignCenter
	case "right":
		return TextAlignRight
	default:
		return fallback
	}
}

func tableRowLabelWidth(labels []string, dataCellW float64) float64 {
	maxLen := 0
	for _, label := range labels {
		maxLen = max(maxLen, len([]rune(label)))
	}
	width := 0.015 + float64(maxLen)*0.025
	if width < 0.04 {
		width = 0.04
	}
	if dataCellW > 0 && width > dataCellW*0.5 {
		width = dataCellW * 0.5
	}
	return width
}

func tableCellRect(bbox geom.Rect, gridRows, dataCols int, hasRowLabels, hasColLabels bool, rowLabelW float64, row, col int) geom.Rect {
	if gridRows <= 0 || dataCols <= 0 {
		return geom.Rect{}
	}
	cellH := bbox.H() / float64(gridRows)
	y0 := bbox.Max.Y - float64(row+1)*cellH
	y1 := bbox.Max.Y - float64(row)*cellH
	if hasRowLabels && col == 0 {
		if hasColLabels && row == 0 {
			return geom.Rect{}
		}
		return geom.Rect{
			Min: geom.Pt{X: bbox.Min.X - rowLabelW, Y: y0},
			Max: geom.Pt{X: bbox.Min.X, Y: y1},
		}
	}

	dataCol := col
	if hasRowLabels {
		dataCol--
	}
	if dataCol < 0 || dataCol >= dataCols {
		return geom.Rect{}
	}
	cellW := bbox.W() / float64(dataCols)
	x0 := bbox.Min.X + float64(dataCol)*cellW
	return geom.Rect{
		Min: geom.Pt{X: x0, Y: y0},
		Max: geom.Pt{X: x0 + cellW, Y: y1},
	}
}

func tableTextAnchor(rect geom.Rect, align TextAlign) geom.Pt {
	x := rect.Min.X + rect.W()/2
	switch align {
	case TextAlignLeft:
		x = rect.Min.X + rect.W()*0.1
	case TextAlignRight:
		x = rect.Max.X - rect.W()*0.1
	}
	return geom.Pt{
		X: x,
		Y: rect.Min.Y + rect.H()/2,
	}
}

// Draw renders the wedge path using the embedded patch styling.
func (w *Wedge) Draw(ren render.Renderer, ctx *DrawContext) {
	if w == nil || ctx == nil || ren == nil || w.Radius <= 0 {
		return
	}
	path := buildDisplayPath(ctx, w.Coords, w.localPath(), geom.Identity())
	w.drawStyledPath(ren, path, geom.Path{})
}

// Bounds returns the wedge's data-space bounds when applicable.
func (w *Wedge) Bounds(*DrawContext) geom.Rect {
	if w == nil || w.Radius <= 0 || !isDataCoords(w.Coords) {
		return geom.Rect{}
	}
	bounds, _ := pathBounds(w.localPath())
	return bounds
}

func (w *Wedge) localPath() geom.Path {
	outer := specialtyArcPoints(w.Center, w.Radius, w.Theta1, w.Theta2)
	if len(outer) == 0 {
		return geom.Path{}
	}
	if w.Width <= 0 || w.Width >= w.Radius {
		points := make([]geom.Pt, 0, len(outer)+1)
		points = append(points, w.Center)
		points = append(points, outer...)
		return polygonPath(points, true)
	}
	inner := specialtyArcPoints(w.Center, w.Radius-w.Width, w.Theta2, w.Theta1)
	points := make([]geom.Pt, 0, len(outer)+len(inner))
	points = append(points, outer...)
	points = append(points, inner...)
	return polygonPath(points, true)
}

// Draw renders the table cells and text labels.
func (t *Table) Draw(r render.Renderer, ctx *DrawContext) {
	if t == nil || ctx == nil || r == nil || len(t.Cells) == 0 || len(t.Cells[0]) == 0 {
		return
	}
	textRen, ok := r.(render.TextDrawer)
	if !ok {
		return
	}

	for row := range t.Cells {
		for col := range t.Cells[row] {
			cell := t.Cells[row][col]
			if cell.Rect == (geom.Rect{}) {
				continue
			}
			path := buildDisplayPath(ctx, t.Coords, patchRectPath(cell.Rect), geom.Identity())
			r.Path(path, &render.Paint{
				Fill:      cell.Fill,
				Stroke:    t.EdgeColor,
				LineWidth: t.LineWidth,
				LineJoin:  render.JoinMiter,
				LineCap:   render.CapButt,
			})

			text := cell.Text
			if displayTextIsEmpty(text) {
				continue
			}
			anchor := transformedPoint(ctx, t.Coords, tableTextAnchor(cell.Rect, cell.HAlign), 0, 0)
			layout := measureSingleLineTextLayout(r, text, t.FontSize, ctx.RC.FontKey, ctx.RC.UseTeX)
			color := t.TextColor
			if cell.IsHeader {
				color = t.HeaderTextColor
			}
			drawDisplayText(textRen, text, alignedSingleLineOrigin(anchor, layout, cell.HAlign, textLayoutVAlignCenter), t.FontSize, color, ctx.RC.FontKey, ctx.RC.UseTeX)
		}
	}
}

// Bounds returns an empty rect so table placement does not affect autoscaling.
func (t *Table) Bounds(*DrawContext) geom.Rect { return geom.Rect{} }

// Z returns the table's draw order.
func (t *Table) Z() float64 { return t.z }

type specialtyViolinSummary struct {
	min    float64
	max    float64
	mean   float64
	median float64
}

func specialtyArcPoints(center geom.Pt, radius, theta1, theta2 float64) []geom.Pt {
	if radius <= 0 {
		return nil
	}
	span := theta2 - theta1
	steps := max(24, int(math.Ceil(math.Abs(span)/3))+1)
	points := make([]geom.Pt, 0, steps)
	for i := range steps {
		t := float64(i) / float64(max(steps-1, 1))
		angle := (theta1 + span*t) * math.Pi / 180
		points = append(points, geom.Pt{
			X: center.X + radius*math.Cos(angle),
			Y: center.Y + radius*math.Sin(angle),
		})
	}
	return points
}

func specialtyHexagon(center geom.Pt, rx, ry float64) []geom.Pt {
	return []geom.Pt{
		{X: center.X + rx, Y: center.Y - ry/2},
		{X: center.X + rx, Y: center.Y + ry/2},
		{X: center.X, Y: center.Y + ry},
		{X: center.X - rx, Y: center.Y + ry/2},
		{X: center.X - rx, Y: center.Y - ry/2},
		{X: center.X, Y: center.Y - ry},
	}
}

func matplotlibHexbinCenter(x, y, xMin, yMin float64, gridX, gridY int, xStep, yStep float64) (hexbinKey, geom.Pt, bool) {
	ix := (x - xMin) / xStep
	iy := (y - yMin) / yStep
	ix1 := int(math.Round(ix))
	iy1 := int(math.Round(iy))
	ix2 := int(math.Floor(ix))
	iy2 := int(math.Floor(iy))

	valid1 := 0 <= ix1 && ix1 <= gridX && 0 <= iy1 && iy1 <= gridY
	valid2 := 0 <= ix2 && ix2 < gridX && 0 <= iy2 && iy2 < gridY
	if !valid1 && !valid2 {
		return hexbinKey{}, geom.Pt{}, false
	}
	d1 := math.Inf(1)
	if valid1 {
		d1 = (ix-float64(ix1))*(ix-float64(ix1)) + 3*(iy-float64(iy1))*(iy-float64(iy1))
	}
	d2 := math.Inf(1)
	if valid2 {
		d2 = (ix-float64(ix2)-0.5)*(ix-float64(ix2)-0.5) + 3*(iy-float64(iy2)-0.5)*(iy-float64(iy2)-0.5)
	}
	if d1 < d2 {
		return hexbinKey{lattice: 0, row: iy1, col: ix1}, geom.Pt{
			X: xMin + float64(ix1)*xStep,
			Y: yMin + float64(iy1)*yStep,
		}, true
	}
	return hexbinKey{lattice: 1, row: iy2, col: ix2}, geom.Pt{
		X: xMin + (float64(ix2)+0.5)*xStep,
		Y: yMin + (float64(iy2)+0.5)*yStep,
	}, true
}

func specialtyFiniteValues(values []float64) []float64 {
	out := make([]float64, 0, len(values))
	for _, value := range values {
		if isFinite(value) {
			out = append(out, value)
		}
	}
	slices.Sort(out)
	return out
}

func specialtyViolinStats(values []float64) specialtyViolinSummary {
	sum := 0.0
	for _, value := range values {
		sum += value
	}
	return specialtyViolinSummary{
		min:    values[0],
		max:    values[len(values)-1],
		mean:   sum / float64(len(values)),
		median: percentileSorted(values, 50),
	}
}

func specialtyKDE(values []float64, points int, bandwidth float64, methods ...string) ([]float64, []float64) {
	if len(values) == 0 {
		return nil, nil
	}
	minValue := values[0]
	maxValue := values[len(values)-1]
	if minValue == maxValue {
		minValue -= 0.5
		maxValue += 0.5
	}
	if bandwidth <= 0 {
		mean := 0.0
		for _, value := range values {
			mean += value
		}
		mean /= float64(len(values))
		variance := 0.0
		for _, value := range values {
			diff := value - mean
			variance += diff * diff
		}
		std := math.Sqrt(variance / float64(len(values)))
		factor := 1.06
		if len(methods) > 0 {
			switch strings.ToLower(strings.TrimSpace(methods[0])) {
			case "scott":
				factor = 1
			case "silverman", "":
				factor = 1.06
			default:
				if parsed, err := strconv.ParseFloat(methods[0], 64); err == nil && parsed > 0 {
					factor = parsed
				}
			}
		}
		bandwidth = factor * std * math.Pow(float64(len(values)), -0.2)
		if bandwidth <= 0 || !isFinite(bandwidth) {
			bandwidth = (maxValue - minValue) / 12
		}
		if bandwidth <= 0 {
			bandwidth = 1
		}
	}

	grid := make([]float64, points)
	density := make([]float64, points)
	span := maxValue - minValue
	for i := range points {
		t := float64(i) / float64(max(points-1, 1))
		x := minValue + span*t
		grid[i] = x
		sum := 0.0
		for _, value := range values {
			z := (x - value) / bandwidth
			sum += math.Exp(-0.5 * z * z)
		}
		density[i] = sum / (float64(len(values)) * bandwidth * math.Sqrt(2*math.Pi))
	}
	return grid, density
}

func normalizeHexScale(value string) string {
	if strings.EqualFold(strings.TrimSpace(value), "log") {
		return "log"
	}
	return "linear"
}

func specialtyHexbinScaledPoints(x, y []float64, xscale, yscale string) ([]float64, []float64) {
	n := min(len(x), len(y))
	tx := make([]float64, n)
	ty := make([]float64, n)
	for i := range n {
		tx[i], ty[i] = specialtyHexbinScaledPoint(x[i], y[i], xscale, yscale)
	}
	return tx, ty
}

func specialtyHexbinScaledPoint(x, y float64, xscale, yscale string) (float64, float64) {
	if xscale == "log" {
		if x <= 0 {
			x = math.NaN()
		} else {
			x = math.Log10(x)
		}
	}
	if yscale == "log" {
		if y <= 0 {
			y = math.NaN()
		} else {
			y = math.Log10(y)
		}
	}
	return x, y
}

func specialtyHexbinUnscalePoint(pt geom.Pt, xscale, yscale string) geom.Pt {
	if xscale == "log" {
		pt.X = math.Pow(10, pt.X)
	}
	if yscale == "log" {
		pt.Y = math.Pow(10, pt.Y)
	}
	return pt
}

func reduceHexbinValues(entry *hexbinBin, reduce string) float64 {
	if entry == nil {
		return math.NaN()
	}
	switch strings.ToLower(strings.TrimSpace(reduce)) {
	case "sum":
		return entry.sum
	case "count", "len":
		return entry.count
	case "min", "minimum":
		if len(entry.values) == 0 {
			return math.NaN()
		}
		out := entry.values[0]
		for _, v := range entry.values[1:] {
			out = math.Min(out, v)
		}
		return out
	case "max", "maximum", "amax":
		if len(entry.values) == 0 {
			return math.NaN()
		}
		out := entry.values[0]
		for _, v := range entry.values[1:] {
			out = math.Max(out, v)
		}
		return out
	default:
		if entry.count == 0 {
			return math.NaN()
		}
		return entry.sum / entry.count
	}
}

func applyHexbinBins(values []float64, cfg HexbinOptions) []float64 {
	if cfg.BinCount <= 0 && len(cfg.BinEdges) == 0 {
		return values
	}
	out := append([]float64(nil), values...)
	edges := append([]float64(nil), cfg.BinEdges...)
	if len(edges) == 0 && cfg.BinCount > 1 {
		minValue, maxValue := finiteRange(out)
		if isFinite(minValue) && isFinite(maxValue) && minValue != maxValue {
			steps := cfg.BinCount - 1
			for i := 0; i < steps; i++ {
				edges = append(edges, minValue+(maxValue-minValue)*float64(i)/float64(steps))
			}
		}
	}
	if len(edges) == 0 {
		return out
	}
	slices.Sort(edges)
	for i, value := range out {
		out[i] = float64(slices.IndexFunc(edges, func(edge float64) bool {
			return value < edge
		}))
		if out[i] < 0 {
			out[i] = float64(len(edges))
		}
	}
	return out
}

func specialtyHexbinMarginals(x, y []float64, cfg HexbinOptions, mapping ScalarMapInfo) (*PolyCollection, *PolyCollection) {
	extent := cfg.Extent
	if extent == nil {
		rect := finitePointRect(x, y)
		extent = &rect
	}
	gridX := max(1, cfg.GridSizeX)
	gridY := cfg.GridSizeY
	if gridY <= 0 {
		gridY = max(1, int(float64(gridX)/math.Sqrt(3)))
	}
	hbar := specialtyMarginalBars(x, extent.Min.X, extent.Max.X, gridX, true, mapping, cfg.Alpha)
	vbar := specialtyMarginalBars(y, extent.Min.Y, extent.Max.Y, gridY, false, mapping, cfg.Alpha)
	return hbar, vbar
}

func specialtyMarginalBars(values []float64, minValue, maxValue float64, bins int, horizontal bool, mapping ScalarMapInfo, alpha float64) *PolyCollection {
	if bins <= 0 || minValue == maxValue {
		return nil
	}
	counts := make([]float64, bins)
	step := (maxValue - minValue) / float64(bins)
	for _, value := range values {
		if !isFinite(value) {
			continue
		}
		idx := int(math.Floor((value - minValue) / step))
		if idx < 0 || idx >= bins {
			continue
		}
		counts[idx]++
	}
	polys := make([][]geom.Pt, 0, bins)
	colors := make([]render.Color, 0, bins)
	maxCount := 0.0
	for _, count := range counts {
		maxCount = math.Max(maxCount, count)
	}
	if maxCount == 0 {
		return nil
	}
	for i, count := range counts {
		if count == 0 {
			continue
		}
		a := minValue + float64(i)*step
		b := a + step
		thick := 0.05 * count / maxCount
		if horizontal {
			polys = append(polys, []geom.Pt{{X: a, Y: 0}, {X: b, Y: 0}, {X: b, Y: thick}, {X: a, Y: thick}})
		} else {
			polys = append(polys, []geom.Pt{{X: 0, Y: a}, {X: thick, Y: a}, {X: thick, Y: b}, {X: 0, Y: b}})
		}
		colors = append(colors, mapping.Color(count, alpha))
	}
	if len(polys) == 0 {
		return nil
	}
	return &PolyCollection{
		PatchCollection: PatchCollection{
			Collection: Collection{Alpha: 1, z: 1.9},
			FaceColors: colors,
			EdgeColor:  render.Color{},
			EdgeWidth:  0,
		},
		Polygons: polys,
	}
}

func normalizeViolinOrientation(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "horizontal", "h", "x":
		return "horizontal"
	default:
		return "vertical"
	}
}

func normalizeViolinSide(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "low", "left", "bottom":
		return "low"
	case "high", "right", "top":
		return "high"
	default:
		return "both"
	}
}

func violinPoint(posAxis, valueAxis float64, orientation string) geom.Pt {
	if orientation == "horizontal" {
		return geom.Pt{X: valueAxis, Y: posAxis}
	}
	return geom.Pt{X: posAxis, Y: valueAxis}
}

func violinPerpSegment(position, width, value float64, orientation, side string) []geom.Pt {
	low := position - width*0.25
	high := position + width*0.25
	switch side {
	case "low":
		high = position
	case "high":
		low = position
	}
	return []geom.Pt{violinPoint(low, value, orientation), violinPoint(high, value, orientation)}
}

func violinParallelSegment(position, minValue, maxValue float64, orientation string) []geom.Pt {
	return []geom.Pt{violinPoint(position, minValue, orientation), violinPoint(position, maxValue, orientation)}
}

func violinQuantiles(quantiles [][]float64, i int, values []float64) []float64 {
	if i >= len(quantiles) {
		return nil
	}
	out := make([]float64, 0, len(quantiles[i]))
	for _, q := range quantiles[i] {
		if q < 0 || q > 1 || !isFinite(q) {
			continue
		}
		out = append(out, percentileSorted(values, q*100))
	}
	return out
}

func finitePointRect(x, y []float64) geom.Rect {
	var rect geom.Rect
	have := false
	for i := 0; i < min(len(x), len(y)); i++ {
		if !isFinite(x[i]) || !isFinite(y[i]) {
			continue
		}
		pt := geom.Pt{X: x[i], Y: y[i]}
		if !have {
			rect = geom.Rect{Min: pt, Max: pt}
			have = true
			continue
		}
		rect = expandRect(rect, pt)
	}
	if !have {
		return geom.Rect{Min: geom.Pt{}, Max: geom.Pt{X: 1, Y: 1}}
	}
	return rect
}

func piePoint(center geom.Pt, radius, angleDeg float64) geom.Pt {
	rad := angleDeg * math.Pi / 180
	return geom.Pt{
		X: center.X + radius*math.Cos(rad),
		Y: center.Y + radius*math.Sin(rad),
	}
}

func pieAlign(angleDeg float64) TextAlign {
	rad := angleDeg * math.Pi / 180
	switch {
	case math.Cos(rad) < -0.2:
		return TextAlignRight
	case math.Cos(rad) > 0.2:
		return TextAlignLeft
	default:
		return TextAlignCenter
	}
}

func pieLabelRotation(angleDeg float64, enabled bool) float64 {
	if !enabled {
		return 0
	}
	angle := math.Mod(angleDeg, 360)
	if angle < 0 {
		angle += 360
	}
	if angle > 90 && angle < 270 {
		angle += 180
	}
	return math.Mod(angle, 360)
}

func floatAt(values []float64, i int, fallback float64) float64 {
	if i < len(values) && isFinite(values[i]) {
		return values[i]
	}
	return fallback
}

func boolOffset(v bool) int {
	if v {
		return 1
	}
	return 0
}

func specialtyBool(value *bool, fallback bool) bool {
	if value == nil {
		return fallback
	}
	return *value
}

func hideAxesFrame(a *Axes) {
	if a == nil {
		return
	}
	a.ShowFrame = false
	for _, axis := range []*Axis{a.XAxis, a.YAxis, a.XAxisTop, a.YAxisRight} {
		if axis == nil {
			continue
		}
		axis.ShowSpine = false
		axis.ShowTicks = false
		axis.ShowLabels = false
	}
}
