package pgf

import (
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/cwbudde/matplotlib-go/render"
)

// SetPGFOptions implements render.PGFOptionSetter.
func (r *Renderer) SetPGFOptions(opts render.PGFOptions) {
	r.pgfOpts = normalizePGFOptions(opts)
}

// SavePGF writes the finalized PGF document to path.
func (r *Renderer) SavePGF(path string) error {
	if len(r.document) == 0 {
		return errors.New("pgf: SavePGF called before End")
	}
	return os.WriteFile(path, r.document, 0o644)
}

// SavePGFWithOptions writes the finalized PGF document to path using opts for
// export-time options.
func (r *Renderer) SavePGFWithOptions(path string, opts render.PGFOptions) error {
	if len(r.document) == 0 {
		return errors.New("pgf: SavePGFWithOptions called before End")
	}
	r.SetPGFOptions(opts)
	return os.WriteFile(path, []byte(r.documentWithOptions(r.pgfOpts)), 0o644)
}

func (r *Renderer) documentWithOptions(opts render.PGFOptions) string {
	body := stripLeadingPGFComments(string(r.document))
	var b strings.Builder
	saved := r.pgfOpts
	r.pgfOpts = opts
	r.writeDocumentComments(&b)
	r.pgfOpts = saved
	b.WriteString(body)
	return b.String()
}

func stripLeadingPGFComments(doc string) string {
	for strings.HasPrefix(doc, "%") {
		lineEnd := strings.IndexByte(doc, '\n')
		if lineEnd < 0 {
			return ""
		}
		doc = doc[lineEnd+1:]
	}
	return doc
}

func (r *Renderer) writeDocumentComments(w *strings.Builder) {
	opts := normalizePGFOptions(r.pgfOpts)
	if opts.CommentPolicy == render.PGFCommentPolicyStrip {
		return
	}
	w.WriteString("% Generated by matplotlib-go\n")
	if len(opts.Metadata) > 0 {
		keys := make([]string, 0, len(opts.Metadata))
		for key := range opts.Metadata {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(w, "%% metadata %s: %s\n", escapePGFComment(key), escapePGFComment(opts.Metadata[key]))
		}
	}
	for _, line := range opts.Preamble {
		if strings.TrimSpace(line) == "" {
			continue
		}
		fmt.Fprintf(w, "%% preamble: %s\n", escapePGFComment(line))
	}
	if opts.VerificationMode != render.PGFVerificationModeNone {
		fmt.Fprintf(w, "%% verification: %s\n", opts.VerificationMode)
	}
}

func normalizePGFOptions(opts render.PGFOptions) render.PGFOptions {
	if opts.CommentPolicy == "" {
		opts.CommentPolicy = render.PGFCommentPolicyKeep
	}
	if opts.VerificationMode == "" {
		opts.VerificationMode = render.PGFVerificationModeNone
	}
	if len(opts.Metadata) > 0 {
		metadata := make(map[string]string, len(opts.Metadata))
		for k, v := range opts.Metadata {
			metadata[k] = v
		}
		opts.Metadata = metadata
	}
	if len(opts.Preamble) > 0 {
		preamble := make([]string, len(opts.Preamble))
		copy(preamble, opts.Preamble)
		opts.Preamble = preamble
	}
	return opts
}

func escapePGFComment(s string) string {
	return strings.NewReplacer("\r", " ", "\n", " ").Replace(s)
}
