package pgf

import (
	"errors"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"

	"github.com/cwbudde/matplotlib-go/internal/geom"
	"github.com/cwbudde/matplotlib-go/render"
)

const defaultFontHeight = 13.0

type state struct {
	inContent bool
}

// Renderer implements render.Renderer by emitting PGF/TikZ commands.
type Renderer struct {
	width      int
	height     int
	background render.Color
	resolution uint

	began      bool
	content    strings.Builder
	document   []byte
	stack      []state
	colorNames map[string]string
}

var (
	_ render.Renderer              = (*Renderer)(nil)
	_ render.PGFExporter           = (*Renderer)(nil)
	_ render.DPIAware              = (*Renderer)(nil)
	_ render.FontTextDrawer        = (*Renderer)(nil)
	_ render.FontRotatedTextDrawer = (*Renderer)(nil)
)

// New creates a PGF renderer with a point-sized canvas.
func New(width, height int, background render.Color) (*Renderer, error) {
	if width <= 0 {
		width = 640
	}
	if height <= 0 {
		height = 480
	}
	if background == (render.Color{}) {
		background = render.Color{R: 1, G: 1, B: 1, A: 1}
	}
	return &Renderer{
		width:      width,
		height:     height,
		background: background,
		resolution: 72,
	}, nil
}

// SetResolution implements render.DPIAware.
func (r *Renderer) SetResolution(dpi uint) {
	if dpi == 0 {
		dpi = 72
	}
	r.resolution = dpi
}

// Begin starts a drawing session.
func (r *Renderer) Begin(_ geom.Rect) error {
	if r.began {
		return errors.New("pgf: Begin called twice")
	}
	r.began = true
	r.content.Reset()
	r.document = nil
	r.stack = r.stack[:0]
	r.colorNames = map[string]string{}

	r.content.WriteString("% Generated by matplotlib-go\n")
	r.content.WriteString("\\begingroup\n")
	r.content.WriteString("\\begin{pgfpicture}\n")
	fmt.Fprintf(&r.content, "\\pgfpathrectangle{\\pgfpoint{0pt}{0pt}}{\\pgfpoint{%spt}{%spt}}\n",
		shortFloat(float64(r.width)), shortFloat(float64(r.height)))
	r.content.WriteString("\\pgfusepath{use as bounding box}\n")
	fmt.Fprintf(&r.content, "\\pgftransformcm{1}{0}{0}{-1}{\\pgfpoint{0pt}{%spt}}\n", shortFloat(float64(r.height)))
	if r.background.A > 0 {
		writeFillColor(&r.content, r.colorName(r.background))
		fmt.Fprintf(&r.content, "\\pgfpathrectangle{\\pgfpoint{0pt}{0pt}}{\\pgfpoint{%spt}{%spt}}\n",
			shortFloat(float64(r.width)), shortFloat(float64(r.height)))
		r.content.WriteString("\\pgfusepath{fill}\n")
	}
	return nil
}

// End finalizes the PGF document.
func (r *Renderer) End() error {
	if !r.began {
		return errors.New("pgf: End called before Begin")
	}
	r.began = false
	r.content.WriteString("\\end{pgfpicture}\n")
	r.content.WriteString("\\endgroup\n")
	r.document = []byte(r.content.String())
	return nil
}

// Save pushes graphics state.
func (r *Renderer) Save() {
	r.stack = append(r.stack, state{inContent: r.began})
	if r.began {
		r.content.WriteString("\\pgfscope\n")
	}
}

// Restore pops graphics state.
func (r *Renderer) Restore() {
	if len(r.stack) == 0 {
		return
	}
	top := r.stack[len(r.stack)-1]
	r.stack = r.stack[:len(r.stack)-1]
	if top.inContent && r.began {
		r.content.WriteString("\\endpgfscope\n")
	}
}

// ClipRect installs a rectangular clip.
func (r *Renderer) ClipRect(rect geom.Rect) {
	if !r.began {
		return
	}
	fmt.Fprintf(&r.content, "\\pgfpathrectangle{\\pgfpoint{%spt}{%spt}}{\\pgfpoint{%spt}{%spt}}\n",
		shortFloat(rect.Min.X), shortFloat(rect.Min.Y), shortFloat(rect.W()), shortFloat(rect.H()))
	r.content.WriteString("\\pgfusepath{clip}\n")
}

// ClipPath installs an arbitrary path clip.
func (r *Renderer) ClipPath(path geom.Path) {
	if !r.began {
		return
	}
	if !writePathOps(&r.content, path) {
		return
	}
	r.content.WriteString("\\pgfusepath{clip}\n")
}

// Path draws a vector path.
func (r *Renderer) Path(path geom.Path, paint *render.Paint) {
	if !r.began || paint == nil {
		return
	}
	hasFill := paint.Fill.A > 0
	hasStroke := paint.Stroke.A > 0 && paint.LineWidth > 0
	if !hasFill && !hasStroke {
		return
	}
	if !writePathOps(&r.content, path) {
		return
	}
	if hasFill {
		writeFillColor(&r.content, r.colorName(paint.Fill))
	}
	if hasStroke {
		writeStrokeColor(&r.content, r.colorName(paint.Stroke))
		lineWidth := paint.LineWidth
		if lineWidth <= 0 {
			lineWidth = 1
		}
		fmt.Fprintf(&r.content, "\\pgfsetlinewidth{%spt}\n", shortFloat(lineWidth))
	}
	switch {
	case hasFill && hasStroke:
		r.content.WriteString("\\pgfusepath{fill,stroke}\n")
	case hasFill:
		r.content.WriteString("\\pgfusepath{fill}\n")
	case hasStroke:
		r.content.WriteString("\\pgfusepath{stroke}\n")
	}
}

// Image is intentionally omitted in the first PGF generator slice.
func (r *Renderer) Image(_ render.Image, _ geom.Rect) {}

// GlyphRun draws glyph IDs as fallback text when possible.
func (r *Renderer) GlyphRun(run render.GlyphRun, textColor render.Color) {
	if !r.began || len(run.Glyphs) == 0 || run.Size <= 0 || textColor.A <= 0 {
		return
	}
	penX := run.Origin.X
	penY := run.Origin.Y
	for _, glyph := range run.Glyphs {
		if glyph.ID != 0 {
			r.DrawTextWithFont(string(rune(glyph.ID)), geom.Pt{X: penX + glyph.Offset.X, Y: penY + glyph.Offset.Y}, run.Size, textColor, run.FontKey)
		}
		advance := glyph.Advance
		if advance == 0 && glyph.ID != 0 {
			advance = r.MeasureText(string(rune(glyph.ID)), run.Size, run.FontKey).W
		}
		penX += advance
	}
}

// MeasureText returns deterministic approximate text metrics for layout.
func (r *Renderer) MeasureText(text string, size float64, _ string) render.TextMetrics {
	if size <= 0 {
		size = defaultFontHeight
	}
	width := 0.6 * size * float64(len([]rune(text)))
	ascent := 0.8 * size
	descent := 0.2 * size
	return render.TextMetrics{W: width, H: ascent + descent, Ascent: ascent, Descent: descent}
}

// DrawText draws text at a baseline origin.
func (r *Renderer) DrawText(text string, origin geom.Pt, size float64, textColor render.Color) {
	r.DrawTextWithFont(text, origin, size, textColor, "")
}

// DrawTextWithFont draws text with an explicit font key. Font selection is
// intentionally left to LaTeX in this generator-only slice.
func (r *Renderer) DrawTextWithFont(text string, origin geom.Pt, size float64, textColor render.Color, _ string) {
	r.writeText(text, origin, size, 0, textColor)
}

// DrawTextRotated draws text rotated around its anchor.
func (r *Renderer) DrawTextRotated(text string, anchor geom.Pt, size, angle float64, textColor render.Color) {
	r.DrawTextRotatedWithFont(text, anchor, size, angle, textColor, "")
}

// DrawTextRotatedWithFont draws rotated text with an explicit font key.
func (r *Renderer) DrawTextRotatedWithFont(text string, anchor geom.Pt, size, angle float64, textColor render.Color, _ string) {
	r.writeText(text, anchor, size, angle, textColor)
}

func (r *Renderer) writeText(text string, origin geom.Pt, size, angle float64, textColor render.Color) {
	if !r.began || text == "" || size <= 0 || textColor.A <= 0 {
		return
	}
	colorName := r.colorName(textColor)
	fmt.Fprintf(&r.content, "\\pgfsetstrokecolor{%s}\n\\pgfsetfillcolor{%s}\n", colorName, colorName)
	rotate := ""
	if angle != 0 && !math.IsNaN(angle) && !math.IsInf(angle, 0) {
		rotate = ",rotate=" + shortFloat(angle)
	}
	fmt.Fprintf(&r.content, "\\pgftext[left,base%s,at=\\pgfpoint{%spt}{%spt}]{\\fontsize{%spt}{%spt}\\selectfont %s}\n",
		rotate, shortFloat(origin.X), shortFloat(origin.Y), shortFloat(size), shortFloat(size*1.2), escapeTeXText(text))
}

// SavePGF writes the finalized PGF document to path.
func (r *Renderer) SavePGF(path string) error {
	if len(r.document) == 0 {
		return errors.New("pgf: SavePGF called before End")
	}
	return os.WriteFile(path, r.document, 0o644)
}

func writePathOps(w *strings.Builder, path geom.Path) bool {
	if !path.Validate() || len(path.C) == 0 {
		return false
	}
	vi := 0
	for _, cmd := range path.C {
		switch cmd {
		case geom.MoveTo:
			pt := path.V[vi]
			vi++
			fmt.Fprintf(w, "\\pgfpathmoveto{\\pgfpoint{%spt}{%spt}}\n", shortFloat(pt.X), shortFloat(pt.Y))
		case geom.LineTo:
			pt := path.V[vi]
			vi++
			fmt.Fprintf(w, "\\pgfpathlineto{\\pgfpoint{%spt}{%spt}}\n", shortFloat(pt.X), shortFloat(pt.Y))
		case geom.QuadTo:
			if vi == 0 {
				vi += 2
				continue
			}
			prev := lastEndpoint(path, vi)
			ctrl := path.V[vi]
			end := path.V[vi+1]
			vi += 2
			c1 := geom.Pt{X: prev.X + (2.0/3.0)*(ctrl.X-prev.X), Y: prev.Y + (2.0/3.0)*(ctrl.Y-prev.Y)}
			c2 := geom.Pt{X: end.X + (2.0/3.0)*(ctrl.X-end.X), Y: end.Y + (2.0/3.0)*(ctrl.Y-end.Y)}
			writeCurve(w, c1, c2, end)
		case geom.CubicTo:
			c1 := path.V[vi]
			c2 := path.V[vi+1]
			end := path.V[vi+2]
			vi += 3
			writeCurve(w, c1, c2, end)
		case geom.ClosePath:
			w.WriteString("\\pgfpathclose\n")
		}
	}
	return true
}

func writeCurve(w *strings.Builder, c1, c2, end geom.Pt) {
	fmt.Fprintf(w, "\\pgfpathcurveto{\\pgfpoint{%spt}{%spt}}{\\pgfpoint{%spt}{%spt}}{\\pgfpoint{%spt}{%spt}}\n",
		shortFloat(c1.X), shortFloat(c1.Y),
		shortFloat(c2.X), shortFloat(c2.Y),
		shortFloat(end.X), shortFloat(end.Y))
}

func lastEndpoint(path geom.Path, vi int) geom.Pt {
	consumed := 0
	for _, cmd := range path.C {
		switch cmd {
		case geom.MoveTo, geom.LineTo:
			consumed++
			if consumed == vi {
				return path.V[consumed-1]
			}
		case geom.QuadTo:
			consumed += 2
			if consumed == vi {
				return path.V[consumed-1]
			}
		case geom.CubicTo:
			consumed += 3
			if consumed == vi {
				return path.V[consumed-1]
			}
		case geom.ClosePath:
		}
	}
	return geom.Pt{}
}

func (r *Renderer) colorName(c render.Color) string {
	c = render.Color{R: clamp01(c.R), G: clamp01(c.G), B: clamp01(c.B), A: clamp01(c.A)}
	key := strings.Join([]string{shortFloat(c.R), shortFloat(c.G), shortFloat(c.B)}, ",")
	if name, ok := r.colorNames[key]; ok {
		return name
	}
	name := fmt.Sprintf("mplgpgfcolor%d", len(r.colorNames)+1)
	r.colorNames[key] = name
	fmt.Fprintf(&r.content, "\\definecolor{%s}{rgb}{%s,%s,%s}\n", name, shortFloat(c.R), shortFloat(c.G), shortFloat(c.B))
	return name
}

func writeFillColor(w *strings.Builder, colorName string) {
	fmt.Fprintf(w, "\\pgfsetfillcolor{%s}\n", colorName)
}

func writeStrokeColor(w *strings.Builder, colorName string) {
	fmt.Fprintf(w, "\\pgfsetstrokecolor{%s}\n", colorName)
}

func clamp01(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}

func shortFloat(v float64) string {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return "0"
	}
	if v == 0 {
		return "0"
	}
	s := strconv.FormatFloat(v, 'f', 6, 64)
	if strings.Contains(s, ".") {
		s = strings.TrimRight(s, "0")
		s = strings.TrimRight(s, ".")
	}
	if s == "" || s == "-0" {
		return "0"
	}
	return s
}

func escapeTeXText(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\textbackslash{}`)
		case '{', '}':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '#', '$', '%', '&', '_':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '^':
			b.WriteString(`\textasciicircum{}`)
		case '~':
			b.WriteString(`\textasciitilde{}`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
