name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  golangci:
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.22", "1.23", "1.24"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m
